In [70]:
#
# hw6pr1iris:  NNETS!  including both clasification + regression for
#    
#              bitwise functions (MAJ + XOR)
#              and our irises  (digits next week)
#

In [71]:
# libraries!
import numpy as np      # numpy is Python's "array" library
import pandas as pd     # Pandas is Python's "data" library ("dataframe" == spreadsheet)

In [72]:
print("+++ Start of MAJ (majority) example +++\n")

# A = np.asarray( [ 
#                     [0,0,0,  0],  # three input bits, one output bit (MAJ)
#                     [0,0,1,  0],   
#                     [0,1,0,  0],  
#                     [0,1,1,  1],   
#                     [1,0,0,  0],  
#                     [1,0,1,  1],   
#                     [1,1,0,  1],  
#                     [1,1,1,  1],
#                 ])

A = np.asarray( [ 
                    [0,0,0,  0],  # three input bits, one output bit (XOR) odd # of 1's
                    [0,0,1,  1],   
                    [0,1,0,  1],  
                    [0,1,1,  0],   
                    [1,0,0,  1],  
                    [1,0,1,  0],   
                    [1,1,0,  0],  
                    [1,1,1,  1],
                ])

X_def = A[:,0:3].copy()   # data by definition in this case
y_def = A[:,3].copy()

def ascii_table(X,y):
    """ print a table of binary inputs and outputs """
    print(f"{'input ':>18s} -> {'pre':<5s} {'des':<5s}") 
    for i in range(len(y)):
        print(f"{X[i,:]!s:>18s} -> {'?':<5s} {y[i]:<5.0f}")   # !s is str ...
        
ascii_table(X_def,y_def)

+++ Start of MAJ (majority) example +++

            input  -> pre   des  
           [0 0 0] -> ?     0    
           [0 0 1] -> ?     1    
           [0 1 0] -> ?     1    
           [0 1 1] -> ?     0    
           [1 0 0] -> ?     1    
           [1 0 1] -> ?     0    
           [1 1 0] -> ?     0    
           [1 1 1] -> ?     1    


In [73]:
#
# we can scramble the remaining data if we want to...
# 
SCRAMBLE = False
if SCRAMBLE == True:
    NUM_ROWS = len(y_def)
    indices = np.random.permutation(NUM_ROWS)  # this scrambles the data each time
    X_all = X_def[indices]
    y_all = y_def[indices]
else:
    X_all = X_def  # don't scramble
    y_all = y_def

ascii_table(X_all,y_all)

            input  -> pre   des  
           [0 0 0] -> ?     0    
           [0 0 1] -> ?     1    
           [0 1 0] -> ?     1    
           [0 1 1] -> ?     0    
           [1 0 0] -> ?     1    
           [1 0 1] -> ?     0    
           [1 1 0] -> ?     0    
           [1 1 1] -> ?     1    


In [74]:
#
# here, we are going to "cheat" by letting the full dataset 
# be both our training and testing sets.  
#    We don't really need both pairs, but no worries.
#
X_train = X_all.copy()
y_train = y_all.copy()

X_test = X_all.copy()
y_test = y_all.copy()

ascii_table(X_train,y_train)

            input  -> pre   des  
           [0 0 0] -> ?     0    
           [0 0 1] -> ?     1    
           [0 1 0] -> ?     1    
           [0 1 1] -> ?     0    
           [1 0 0] -> ?     1    
           [1 0 1] -> ?     0    
           [1 1 0] -> ?     0    
           [1 1 1] -> ?     1    


In [75]:
#
# for many NNets, it's important to keep the feature values in the -1-to-1 range
#    This is done through the "StandardScaler" in scikit-learn
# 
USE_SCALER = False   # this variable is important! It tracks if we need to use the scaler...

# we "train the scaler"  (computes the mean and standard deviation)
if USE_SCALER == True:
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    # Scale with the training data! ave becomes 0; stdev becomes 1
    scaler.fit(X_train)   
    
if USE_SCALER == True:    # if we're using the scaler, all inputs need to be scaled...
    X_train_scaled = scaler.transform(X_train) # scale!
    X_test_scaled = scaler.transform(X_test) # scale!
    print("USING the input scaler:\n")
else:
    X_train_scaled = X_train  # not using the scaler
    X_test_scaled = X_test  # not using the scaler
    print("NOT using the input scaler:\n")
    
y_train_scaled = y_train  # the predicted/desired labels are not scaled
y_test_scaled = y_test  # not using the scaler
    
ascii_table(X_train_scaled,y_train_scaled)

NOT using the input scaler:

            input  -> pre   des  
           [0 0 0] -> ?     0    
           [0 0 1] -> ?     1    
           [0 1 0] -> ?     1    
           [0 1 1] -> ?     0    
           [1 0 0] -> ?     1    
           [1 0 1] -> ?     0    
           [1 1 0] -> ?     0    
           [1 1 1] -> ?     1    


In [76]:
#
# import our NNet library (within scikit-learn)
#       import error?  run a cell with !conda update scikit-learn
#
from sklearn.neural_network import MLPClassifier   #multilayer perceptron

#
# Here's where you can change the number of layers, neurons, and other parameters:
#
nn_classifier = MLPClassifier(hidden_layer_sizes=(4,), max_iter=200, activation="tanh",
                    solver='sgd', verbose=True, shuffle=True,
                    random_state=None, # reproduceability!
                    learning_rate_init=.1, learning_rate = 'adaptive')

# documentation:
# scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html 
#     Try verbose / activation "relu" / other network sizes ...

print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
nn_classifier.fit(X_train_scaled, y_train_scaled)
print("\n\n++++++++++  TRAINING:   end  +++++++++++++++\n\n")

print(f"The analog prediction error (the loss) is {nn_classifier.loss_}")



++++++++++  TRAINING:  begin  +++++++++++++++


Iteration 1, loss = 0.77287405
Iteration 2, loss = 0.76179070
Iteration 3, loss = 0.74908735
Iteration 4, loss = 0.73709581
Iteration 5, loss = 0.72732093
Iteration 6, loss = 0.72033390
Iteration 7, loss = 0.71593477
Iteration 8, loss = 0.71345882
Iteration 9, loss = 0.71209421
Iteration 10, loss = 0.71112165
Iteration 11, loss = 0.71004400
Iteration 12, loss = 0.70861696
Iteration 13, loss = 0.70681188
Iteration 14, loss = 0.70474500
Iteration 15, loss = 0.70260041
Iteration 16, loss = 0.70056526
Iteration 17, loss = 0.69878592
Iteration 18, loss = 0.69734670
Iteration 19, loss = 0.69626795
Iteration 20, loss = 0.69551752
Iteration 21, loss = 0.69502930
Iteration 22, loss = 0.69472322
Iteration 23, loss = 0.69452235
Iteration 24, loss = 0.69436473
Iteration 25, loss = 0.69420907
Iteration 26, loss = 0.69403506
Iteration 27, loss = 0.69383962
Iteration 28, loss = 0.69363105
Iteration 29, loss = 0.69342280
Iteration 30, loss = 0.69322821

In [77]:
#
# what can we see about our nnet?
#
#
# how did it do on the training data?   (It's the same as the testing data, in this case!)
#

#
# which one do we want: classifier or regressor?
#

def ascii_table_for_classifier(X,y,nn):
    """ a table including predictions using nn.predict """
    predictions = nn.predict(X) # all predictions
    prediction_probs = nn.predict_proba(X) # all prediction probabilities
    # count correct
#     print(predictions)
#     print(prediction_probs)
    num_correct = 0
    # printing
    
    print(f"{'input ':>18s} -> {'pred':^6s} {'desr':^6s}") 
    for i in range(len(y)):
        pred = predictions[i]
        pred_probs = prediction_probs[i,:]
        desired = y[i]
        if pred != desired: result = "  incorrect: " + str(pred_probs)
        else: result = ""; num_correct += 1
        # could use X_train below to show the unscaled, if sought...
        print(f"{X[i,:]!s:>18s} -> {pred:^6.0f} {desired:^6.0f} {result:^10s}") 
    print(f"\ncorrect predictions: {num_correct} out of {len(y)}")
    


#
# let's see how it did on the test data (also the training data!)
#
ascii_table_for_classifier(X_test_scaled,
                           y_test_scaled,
                           nn_classifier)   # this is our own f'n, above
#
# other things...
#
nn = nn_classifier  # less to type?
print("\n\n+++++ parameters, weights, etc. +++++\n")
print(f"\nweights/coefficients:\n")
for wts in nn.coefs_:
    print(wts)
print(f"\nintercepts: {nn.intercepts_}")
print(f"\nall parameters: {nn.get_params()}")

            input  ->  pred   desr 
           [0 0 0] ->   1      0      incorrect: [0.48554165 0.51445835]
           [0 0 1] ->   1      1              
           [0 1 0] ->   0      1      incorrect: [0.52278683 0.47721317]
           [0 1 1] ->   0      0              
           [1 0 0] ->   1      1              
           [1 0 1] ->   0      0              
           [1 1 0] ->   0      0              
           [1 1 1] ->   0      1      incorrect: [0.52873967 0.47126033]

correct predictions: 5 out of 8


+++++ parameters, weights, etc. +++++


weights/coefficients:

[[-0.91722979  0.09826731 -0.14541562  0.18204201]
 [-0.34923858  0.1812823   0.08239441 -0.34065874]
 [ 0.6524091   0.84851153 -0.6849058  -0.77400868]]
[[ 0.28503503]
 [ 0.02972361]
 [-0.10951727]
 [ 0.50178926]]

intercepts: [array([-0.86837788, -0.58654872, -0.28976761, -0.55468155]), array([0.49524402])]

all parameters: {'activation': 'tanh', 'alpha': 0.0001, 'batch_size': 'auto', 'beta_1': 0.9, 'beta_2

In [78]:
#
# we have a predictive model!  Let's try it out...
#

def make_prediction( Features, nn ):
    """ be sure that Features has the right shape! """
    row = np.array( [Features] )  # makes an array-row
    if USE_SCALER == True:
        row = scaler.transform(row)
    print("input features are", row)
    print("nn.predict_proba == ", nn.predict_proba(row))
    prediction = nn.predict(row)
    return prediction
    
# our features
Features = [ 0.2, 0.65, 0.7 ]
prediction = make_prediction(Features, nn_classifier)
print(f"prediction: {prediction}")

input features are [[0.2  0.65 0.7 ]]
nn.predict_proba ==  [[0.5134946 0.4865054]]
prediction: [0]


In [79]:
#
# NNets are more natural regressors than classifiers...
#
#   That is, they naturally output continuous, floating-point values
#   instead of a category or choice-among-labels.
#
#   So, let's try to predict our binary function as a floating point output instead...
#

In [80]:
#
# MLPRegressor predicts floating-point outputs
#

from sklearn.neural_network import MLPRegressor

nn_regressor = MLPRegressor(hidden_layer_sizes=(4,), max_iter=200, activation="tanh",
                    solver='sgd', verbose=False, shuffle=True,
                    random_state=None, # reproduceability!
                    learning_rate_init=.1, learning_rate = 'adaptive')

print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
nn_regressor.fit(X_train, y_train)
print("\n\n++++++++++  TRAINING:   end  +++++++++++++++\n\n")

print(f"The (squared) prediction error (the loss) is {nn_regressor.loss_}")



++++++++++  TRAINING:  begin  +++++++++++++++




++++++++++  TRAINING:   end  +++++++++++++++


The (squared) prediction error (the loss) is 0.00020034328475695065


/Users/chiachinghsieh/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:617: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [81]:
#
# how did it do? now we're making progress (by regressing)
#

def ascii_table_for_regressor(X,y,nn):
    """ a table including predictions using nn.predict """
    predictions = nn.predict(X) # all predictions
    # measure error
    error = 0.0
    # printing
    print(f"{'input ':>18s} ->  {'pred':^6s}  {'desr':^6s}  {'absdiff':^10s}") 
    for i in range(len(y)):
        pred = predictions[i]
        desired = y[i]
        result = abs(desired - pred)
        error += result
        print(f"{X[i,:]!s:>18s} ->  {pred:<+6.3f}  {desired:<+6.3f}  {result:^10.3f}") 
    print(f"\naverage abs error: {error/len(y)}")
    


#
# let's see how it did on the test data (also the training data!)
#
ascii_table_for_regressor(X_test_scaled,
                          y_test_scaled,
                          nn_regressor)   # this is our own f'n, above
#
# other things...
#
nn = nn_regressor  # less to type?
print("\n\n+++++ parameters, weights, etc. +++++\n")
print(f"\nweights/coefficients:\n")
for wts in nn.coefs_:
    print(wts)
print(f"\nintercepts: {nn.intercepts_}")
print(f"\nall parameters: {nn.get_params()}")

            input  ->   pred    desr    absdiff  
           [0 0 0] ->  -0.001  +0.000    0.001   
           [0 0 1] ->  +1.000  +1.000    0.000   
           [0 1 0] ->  +1.018  +1.000    0.018   
           [0 1 1] ->  -0.008  +0.000    0.008   
           [1 0 0] ->  +1.006  +1.000    0.006   
           [1 0 1] ->  -0.009  +0.000    0.009   
           [1 1 0] ->  -0.015  +0.000    0.015   
           [1 1 1] ->  +1.012  +1.000    0.012   

average abs error: 0.008829880592530842


+++++ parameters, weights, etc. +++++


weights/coefficients:

[[-1.75404937 -0.75348188  0.17248849 -0.78518314]
 [ 2.02597199  0.89119138  0.01290878  0.97679192]
 [-1.8313514  -0.68939382  0.65523024 -0.71254168]]
[[-1.7386689 ]
 [ 1.60021224]
 [-0.5215019 ]
 [ 1.49590365]]

intercepts: [array([ 0.75617772,  1.03275051,  0.17818079, -0.5712695 ]), array([0.73343015])]

all parameters: {'activation': 'tanh', 'alpha': 0.0001, 'batch_size': 'auto', 'beta_1': 0.9, 'beta_2': 0.999, 'early_stopping': Fals

In [82]:
#
# again, we have a predictive model, now a regressor.  Let's try it out...
#

def make_prediction( Features, nn ):
    """ be sure that Features has the right shape! """
    row = np.array( [Features] )  # makes an array-row
    if USE_SCALER == True:
        row = scaler.transform(row)
    print("input features are", row)
    prediction = nn.predict(row)
    print("nn.predict(row) == ", prediction)
    return prediction
    
# our features
Features = [ 1.0, 1.0, 1.0 ]
prediction = make_prediction(Features, nn_regressor)
print(f"prediction: {prediction}")

input features are [[1. 1. 1.]]
nn.predict(row) ==  [1.0120869]
prediction: [1.0120869]


In [83]:
#
# Onward to the iris data!
#

In [84]:
ord('\t')

9

In [85]:
# let's read in our flower data...
# 
# for read_csv, use header=0 when row 0 is a header row
# 
filename = 'iris.csv'
df = pd.read_csv(filename, header=0)   # encoding="latin1" et al.
print(f"{filename} : file read into a pandas dataframe.")

iris.csv : file read into a pandas dataframe.


In [86]:
#
# a dataframe is a "spreadsheet in Python"   (seems to have an extra column!)
#
pd.set_option('display.max_rows', 10)     # None for no limit; default: 10
# pd.set_option('display.min_rows', 150)   # min_rows is not universally supported...
# let's view it!
df

sepallen  sepalwid  petallen      petalwid   irisname  \
0         4.6       3.6       1.0  2.000000e-01     setosa   
1         4.3       3.0       1.1  1.000000e-01     setosa   
2         5.0       3.2       1.2  2.000000e-01     setosa   
3         5.8       4.0       1.2  2.000000e-01     setosa   
4         4.4       3.0       1.3  2.000000e-01     setosa   
..        ...       ...       ...           ...        ...   
138       7.7       3.8       6.7  2.200000e+00  virginica   
139       7.7       2.8       6.7  2.000000e+00  virginica   
140       7.7       2.6       6.9  2.300000e+00  virginica   
141       4.2      42.0    4242.0  4.200000e+42  alieniris   
142       4.2      42.0    4242.0  4.200000e+42        NaN   

     adapted from https://en.wikipedia.org/wiki/Iris_flower_data_set  
0                                                  NaN                
1                                                  NaN                
2                                                  NaN                
3                                                  NaN                
4                                                  NaN                
..                                                 ...                
138                                                NaN                
139                                                NaN                
140                                                NaN                
141                                                NaN                
142                                                NaN                

[143 rows x 6 columns]

In [87]:
#
# let's look at our pandas dataframe   (Aargh: that extra column!)
#
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 6 columns):
 #   Column                                                           Non-Null Count  Dtype  
---  ------                                                           --------------  -----  
 0   sepallen                                                         143 non-null    float64
 1   sepalwid                                                         143 non-null    float64
 2   petallen                                                         143 non-null    float64
 3   petalwid                                                         143 non-null    float64
 4   irisname                                                         142 non-null    object 
 5   adapted from https://en.wikipedia.org/wiki/Iris_flower_data_set  0 non-null      float64
dtypes: float64(5), object(1)
memory usage: 6.8+ KB


In [88]:
#
# let's drop that last column (dropping is usually by _name_):
#
#   if you want a list of the column names use df.columns
col5name = df.columns[5]  # get column name at index 5
df_clean = df.drop(columns=[col5name])  # drop by name is typical
df_clean.info()                         # should be happier!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   sepallen  143 non-null    float64
 1   sepalwid  143 non-null    float64
 2   petallen  143 non-null    float64
 3   petalwid  143 non-null    float64
 4   irisname  142 non-null    object 
dtypes: float64(4), object(1)
memory usage: 5.7+ KB


In [89]:
#
# let's keep our column names in variables, for reference
#
COLUMNS = df_clean.columns            # "list" of columns
print(f"COLUMNS is {COLUMNS}\n")  
  # It's a "pandas" list, called an Index
  # use it just as a Python list of strings:
print(f"COLUMNS[0] is {COLUMNS[0]}\n")

# let's create a dictionary to look up any column index by name
COL_INDEX = {}
for i, name in enumerate(COLUMNS):
    COL_INDEX[name] = i  # using the name (as key), look up the value (i)
print(f"COL_INDEX is {COL_INDEX}")

COLUMNS is Index(['sepallen', 'sepalwid', 'petallen', 'petalwid', 'irisname'], dtype='object')

COLUMNS[0] is sepallen

COL_INDEX is {'sepallen': 0, 'sepalwid': 1, 'petallen': 2, 'petalwid': 3, 'irisname': 4}


In [90]:
#
# let's look at our cleaned-up dataframe...
#
df_clean.info()   
#
# notice that the non-null is _different_ for irisname!
df_clean   # show a table! (the problem rows are the last two...)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   sepallen  143 non-null    float64
 1   sepalwid  143 non-null    float64
 2   petallen  143 non-null    float64
 3   petalwid  143 non-null    float64
 4   irisname  142 non-null    object 
dtypes: float64(4), object(1)
memory usage: 5.7+ KB


sepallen  sepalwid  petallen      petalwid   irisname
0         4.6       3.6       1.0  2.000000e-01     setosa
1         4.3       3.0       1.1  1.000000e-01     setosa
2         5.0       3.2       1.2  2.000000e-01     setosa
3         5.8       4.0       1.2  2.000000e-01     setosa
4         4.4       3.0       1.3  2.000000e-01     setosa
..        ...       ...       ...           ...        ...
138       7.7       3.8       6.7  2.200000e+00  virginica
139       7.7       2.8       6.7  2.000000e+00  virginica
140       7.7       2.6       6.9  2.300000e+00  virginica
141       4.2      42.0    4242.0  4.200000e+42  alieniris
142       4.2      42.0    4242.0  4.200000e+42        NaN

[143 rows x 5 columns]

In [91]:
#
# typically, after dropping columns we don't want, 
#   we drop rows with missing data (other approaches are possible, too)
#
df_full = df_clean.dropna()   # this removes all rows with missing data ("na")
df_full.info()                # it's "full" because it has no missing data
df_full
#
# notice that _all_ of the rows now have 142 non-null items
#    also, the last row isn't real data... we'll handle it next

<class 'pandas.core.frame.DataFrame'>
Int64Index: 142 entries, 0 to 141
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   sepallen  142 non-null    float64
 1   sepalwid  142 non-null    float64
 2   petallen  142 non-null    float64
 3   petalwid  142 non-null    float64
 4   irisname  142 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.7+ KB


sepallen  sepalwid  petallen      petalwid   irisname
0         4.6       3.6       1.0  2.000000e-01     setosa
1         4.3       3.0       1.1  1.000000e-01     setosa
2         5.0       3.2       1.2  2.000000e-01     setosa
3         5.8       4.0       1.2  2.000000e-01     setosa
4         4.4       3.0       1.3  2.000000e-01     setosa
..        ...       ...       ...           ...        ...
137       7.6       3.0       6.6  2.100000e+00  virginica
138       7.7       3.8       6.7  2.200000e+00  virginica
139       7.7       2.8       6.7  2.000000e+00  virginica
140       7.7       2.6       6.9  2.300000e+00  virginica
141       4.2      42.0    4242.0  4.200000e+42  alieniris

[142 rows x 5 columns]

In [92]:
# 
# get rid of last row!
#
df_final = df_full.iloc[0:-1]     # not the syntax I would choose
print(df_final.shape)
df_final

(141, 5)


sepallen  sepalwid  petallen  petalwid   irisname
0         4.6       3.6       1.0       0.2     setosa
1         4.3       3.0       1.1       0.1     setosa
2         5.0       3.2       1.2       0.2     setosa
3         5.8       4.0       1.2       0.2     setosa
4         4.4       3.0       1.3       0.2     setosa
..        ...       ...       ...       ...        ...
136       7.9       3.8       6.4       2.0  virginica
137       7.6       3.0       6.6       2.1  virginica
138       7.7       3.8       6.7       2.2  virginica
139       7.7       2.8       6.7       2.0  virginica
140       7.7       2.6       6.9       2.3  virginica

[141 rows x 5 columns]

In [93]:
# all of scikit-learn's ML routines need numbers, not strings
#   ... even for categories/classifications (like species!)
#   so, we will convert the flower-species to numbers:

SPECIES = ['setosa','versicolor','virginica']   # int to str
SPECIES_INDEX = {'setosa':0,'versicolor':1,'virginica':2}  # str to int

def convert_species(speciesname):
    """ return the species index (a unique integer/category) """
    #print(f"converting {speciesname}...")
    return SPECIES_INDEX[speciesname]

# Let's try it out...
for name in SPECIES:
    print(f"{name} maps to {convert_species(name)}")

setosa maps to 0
versicolor maps to 1
virginica maps to 2


In [94]:
#
# we can "apply" a function to a whole column
#   it may give a warning; here, this is ok ...
#

df_final['irisname'] = df_final['irisname'].apply(convert_species)

# Don't run this twice: the data will be different the second time!
#   (In reality, feel free to go back and re-run cells to re-establish things... :-)
#    Don't worry about the (possible)  "SettingWithCopyWarning" here...

/Users/chiachinghsieh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [95]:
#
# let's see it!  (this is safe to run many times...)
#
df_final         # print(df_final.to_string())  # for _all_ rows...

sepallen  sepalwid  petallen  petalwid  irisname
0         4.6       3.6       1.0       0.2         0
1         4.3       3.0       1.1       0.1         0
2         5.0       3.2       1.2       0.2         0
3         5.8       4.0       1.2       0.2         0
4         4.4       3.0       1.3       0.2         0
..        ...       ...       ...       ...       ...
136       7.9       3.8       6.4       2.0         2
137       7.6       3.0       6.6       2.1         2
138       7.7       3.8       6.7       2.2         2
139       7.7       2.8       6.7       2.0         2
140       7.7       2.6       6.9       2.3         2

[141 rows x 5 columns]

In [96]:
#
# let's convert our dataframe to a numpy array, named A
#    Our ML library, scikit-learn operates entirely on numpy arrays.
#
A = df_final.values    # .values gets the numpy array
print(A)

[[4.6 3.6 1.  0.2 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [4.6 3.2 1.4 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.8 3.  1.4 0.3 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.  3.3 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.3 3.7 1.5 0.2 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.  3.5 1.6 0.6 0. ]
 [5.1 3.8 1.6 0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [5.4 3.4 1

In [97]:
#
# let's make sure it's all floating-point, so we can multiply and divide
#
A = A.astype('float64')  # so many:  www.tutorialspoint.com/numpy/numpy_data_types.htm
print(A)

[[4.6 3.6 1.  0.2 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [4.6 3.2 1.4 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.8 3.  1.4 0.3 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.  3.3 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.3 3.7 1.5 0.2 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.  3.5 1.6 0.6 0. ]
 [5.1 3.8 1.6 0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [5.4 3.4 1

In [98]:
#
# nice to have NUM_ROWS and NUM_COLS around
#
NUM_ROWS, NUM_COLS = A.shape
print(f"\nThe dataset has {NUM_ROWS} rows and {NUM_COLS} cols")


The dataset has 141 rows and 5 cols


In [99]:
# let's use all of our variables, to reinforce names...

# choose a row index, n:
n = 132
print(f"flower #{n} is {A[n]}")

for i in range(len(COLUMNS)):
    colname = COLUMNS[i]
    if colname != 'irisname':
        print(f"  Its {colname} is {A[n][i]}")
    else:
        species_num = int(A[n][i])
        species = SPECIES[species_num]
        print(f"  Its {colname} is {species} ({species_num})")

flower #132 is [7.2 3.6 6.1 2.5 2. ]
  Its sepallen is 7.2
  Its sepalwid is 3.6
  Its petallen is 6.1
  Its petalwid is 2.5
  Its irisname is virginica (2)


In [100]:
#
# we could write-our-own, but we don't have to! Let's "library"! After all,
#
#     the representation and storage for the trees is a big task
#     we want an already-debugged algorithm!
#     we want to ask q'ns about irises and how "classifiable" they are, 
#        rather than questions about implementation (at least for this moment...)
#

In [101]:
print("+++ Start of data definitions +++\n")

X_all = A[:,0:4].copy()  # X (features) ... is all rows, columns 0, 1, 2, 3
y_all = A[:,4].copy()    # y (labels) ... is all rows, column 4 only

print(f"X_all (just features: 10 rows) is \n {X_all[:10,:]}")
print(f"y_all (just labels)   is \n {y_all}") 

+++ Start of data definitions +++

X_all (just features: 10 rows) is 
 [[4.6 3.6 1.  0.2]
 [4.3 3.  1.1 0.1]
 [5.  3.2 1.2 0.2]
 [5.8 4.  1.2 0.2]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.7 3.2 1.3 0.2]
 [5.  3.5 1.3 0.3]
 [5.4 3.9 1.3 0.4]]
y_all (just labels)   is 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [102]:
#
# we scramble the data, to give a different TRAIN/TEST split each time...
# 
indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_all = X_all[indices]              # we apply the _same_ permutation to each!
y_all = y_all[indices]              # again...
print("features\n", X_all[:10,:])
print("labels\n",y_all)

features
 [[6.4 3.1 5.5 1.8]
 [7.  3.2 4.7 1.4]
 [6.8 3.2 5.9 2.3]
 [5.7 2.5 5.  2. ]
 [5.  3.3 1.4 0.2]
 [5.4 3.  4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [5.6 2.9 3.6 1.3]
 [5.  3.  1.6 0.2]
 [4.6 3.6 1.  0.2]]
labels
 [2. 1. 2. 2. 0. 1. 0. 1. 0. 0. 1. 1. 2. 2. 2. 0. 2. 2. 1. 2. 2. 2. 2. 2.
 0. 0. 0. 0. 2. 1. 2. 1. 1. 2. 2. 2. 1. 2. 0. 2. 2. 2. 1. 1. 0. 1. 0. 1.
 1. 0. 1. 1. 1. 2. 0. 0. 2. 0. 2. 2. 2. 2. 0. 1. 2. 1. 1. 1. 1. 1. 0. 0.
 0. 0. 2. 0. 0. 1. 1. 2. 2. 1. 0. 0. 0. 0. 1. 1. 2. 1. 1. 2. 1. 2. 0. 0.
 2. 2. 1. 0. 0. 0. 0. 1. 1. 2. 2. 1. 0. 0. 2. 0. 2. 0. 2. 0. 0. 1. 2. 1.
 0. 2. 1. 1. 0. 1. 0. 2. 1. 2. 0. 1. 2. 1. 1. 2. 1. 0. 0. 0. 0.]


In [103]:
#
# We next separate into test data and training data ... 
#    + We will train on the training data...
#    + We will _not_ look at the testing data to build the model
#
# Then, afterward, we will test on the testing data -- and see how well we do!
#

#
# a common convention:  train on 80%, test on 20%    Let's define the TEST_PERCENT
#
NUM_ROWS = X_all.shape[0]     # the number of rows
TEST_PERCENT = 0.20
TEST_SIZE = int(TEST_PERCENT*NUM_ROWS)   # no harm in rounding down

X_test = X_all[:TEST_SIZE]    # first section are for testing
y_test = y_all[:TEST_SIZE]

X_train = X_all[TEST_SIZE:]   # all the rest are for training
y_train = y_all[TEST_SIZE:]

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows" )

training with 113 rows;  testing with 28 rows


In [104]:
print(f"y_test is {y_test}")
print(f"y_train is {y_train}")   # to "get a visual" on these...
# print(X_test)
# print(X_train)

y_test is [2. 1. 2. 2. 0. 1. 0. 1. 0. 0. 1. 1. 2. 2. 2. 0. 2. 2. 1. 2. 2. 2. 2. 2.
 0. 0. 0. 0.]
y_train is [2. 1. 2. 1. 1. 2. 2. 2. 1. 2. 0. 2. 2. 2. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1.
 1. 2. 0. 0. 2. 0. 2. 2. 2. 2. 0. 1. 2. 1. 1. 1. 1. 1. 0. 0. 0. 0. 2. 0.
 0. 1. 1. 2. 2. 1. 0. 0. 0. 0. 1. 1. 2. 1. 1. 2. 1. 2. 0. 0. 2. 2. 1. 0.
 0. 0. 0. 1. 1. 2. 2. 1. 0. 0. 2. 0. 2. 0. 2. 0. 0. 1. 2. 1. 0. 2. 1. 1.
 0. 1. 0. 2. 1. 2. 0. 1. 2. 1. 1. 2. 1. 0. 0. 0. 0.]


In [105]:
#
# for most NNets, it's important to keep the feature values in the -1-to-1 range
#    This is done through the "StandardScaler" in scikit-learn
# 
USE_SCALER = True   # this variable is important! It tracks if we need to use the scaler...

# we "train the scaler"  (computes the mean and standard deviation)
if USE_SCALER == True:
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    # Scale with the training data! ave becomes 0; stdev becomes 1
    scaler.fit(X_train)   
    
if USE_SCALER == True:    # if we're using the scaler, all inputs need to be scaled...
    X_train_scaled = scaler.transform(X_train) # scale!
    X_test_scaled = scaler.transform(X_test) # scale!
    print("USING the input scaler:\n")
else:
    X_train_scaled = X_train.copy()  # not using the scaler
    X_test_scaled = X_test.copy()  # not using the scaler
    print("NOT using the input scaler:\n")
    
y_train_scaled = y_train  # the predicted/desired labels are not scaled
y_test_scaled = y_test  # not using the scaler
    
# ascii_table(X_train_scaled,y_train_scaled)  # unweildy
print(f"X_train_scaled (first 5 rows): {X_train_scaled[:5,:]}")

USING the input scaler:

X_train_scaled (first 5 rows): [[ 2.19823024 -0.03045335  1.6776493   1.25043753]
 [ 0.71524506 -0.25986861  0.34098145  0.17489469]
 [ 0.83882716 -0.03045335  1.21272135  1.38488039]
 [ 0.09733457  0.42837717  0.63156142  0.84710897]
 [ 0.09733457 -0.03045335  0.28286545  0.4437804 ]]


In [106]:
from sklearn.neural_network import MLPClassifier

#
# Here's where you can change the number of hidden layers
# and number of neurons!
#
nn_classifier = MLPClassifier(hidden_layer_sizes=(5,5), max_iter=400, activation="tanh",
                    solver='sgd', verbose=False, shuffle=True,
                    random_state=None, # reproduceability!
                    learning_rate_init=.1, learning_rate = 'adaptive')

print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
nn_classifier.fit(X_train_scaled, y_train_scaled)
print("\n\n++++++++++  TRAINING:   end  +++++++++++++++\n\n")

print(f"The (log) prediction error (the loss) is {nn_classifier.loss_}") 



++++++++++  TRAINING:  begin  +++++++++++++++




++++++++++  TRAINING:   end  +++++++++++++++


The (log) prediction error (the loss) is 0.05180243443839832


In [107]:
#
# how did it do on the testing data?
#

def ascii_table_for_classifier(X,y,nn):
    """ a table including predictions using nn.predict """
    predictions = nn.predict(X) # all predictions
    prediction_probs = nn.predict_proba(X) # all prediction probabilities
    # count correct
    num_correct = 0
    # printing
    print(f"{'flower input ':>18s} -> {'pred':^6s} {'desr':^6s}") 
    for i in range(len(y)):
        pred = predictions[i]
        pred_probs = prediction_probs[i,:]
        desired = y[i]
        if pred != desired: result = "  incorrect: " + str(pred_probs)
        else: result = ""; num_correct += 1
        # can "cheat" in our view by using X_train here...
        print(f"{X[i,:]!s:>18s} -> {pred:^6.0f} {desired:^6.0f} {result:^10s}") 
    print(f"\ncorrect predictions: {num_correct} out of {len(y)}")
    


#
# let's see how it did on the test data (also the training data!)
#
ascii_table_for_classifier(X_test_scaled,
                           y_test_scaled,
                           nn_classifier)   # this is our own f'n, above
#
# other things...
#

# nn = nn_classifier  # less to type?
print("\n\n+++++ parameters, weights, etc. +++++\n")
print(f"\nweights/coefficients:\n")
for wts in nn.coefs_:
    print(wts)
print(f"\nintercepts: {nn.intercepts_}")
print(f"\nall parameters: {nn.get_params()}")

     flower input  ->  pred   desr 
[0.71524506 0.19896191 1.03837337 0.84710897] ->   2      2              
[1.45673765 0.42837717 0.57344542 0.30933754] ->   1      1              
[1.20957346 0.42837717 1.27083734 1.51932325] ->   2      2              
[-0.14982962 -1.17752966  0.7477934   1.11599468] ->   2      2              
[-1.01490431  0.65779243 -1.34438236 -1.30397672] ->   0      0              
[-0.52057592 -0.03045335  0.45721344  0.4437804 ] ->   1      1              
[-0.89132221  1.11662295 -1.34438236 -1.30397672] ->   0      0              
[-0.27341172 -0.25986861 -0.06583051  0.17489469] ->   1      1              
[-1.01490431 -0.03045335 -1.22815037 -1.30397672] ->   0      0              
[-1.50923271  1.34603821 -1.57684634 -1.30397672] ->   0      0              
[ 0.22091667 -0.25986861  0.45721344  0.4437804 ] ->   1      1              
[-0.27341172 -0.03045335  0.45721344  0.4437804 ] ->   1      1              
[2.56897654 1.80486874 1.56141731 1.1159

In [108]:
#
# we could use cross-validation to find the "right"/"best" size and shape of the NNet...
#

#
# but, instead, lets explore a new direction: exploring feature-predictability
#

#
# specifically, here is an example in which we estimate petalwid 
#               from the other four columns -- including the species!
#

In [109]:
df_final

sepallen  sepalwid  petallen  petalwid  irisname
0         4.6       3.6       1.0       0.2         0
1         4.3       3.0       1.1       0.1         0
2         5.0       3.2       1.2       0.2         0
3         5.8       4.0       1.2       0.2         0
4         4.4       3.0       1.3       0.2         0
..        ...       ...       ...       ...       ...
136       7.9       3.8       6.4       2.0         2
137       7.6       3.0       6.6       2.1         2
138       7.7       3.8       6.7       2.2         2
139       7.7       2.8       6.7       2.0         2
140       7.7       2.6       6.9       2.3         2

[141 rows x 5 columns]

In [110]:
#
# regression model for iris petal widths (petalwid, column index 3) 
#

print("+++ Start of regression experiments... +++\n")

X_all = np.concatenate( (A[:,0:3], A[:,4:]),axis=1)  # columns 0, 1, 2, _not_3, and 4
y_all = A[:,3]             # y (labels) ... is all rows, column 3 (petalwid) only

print(f"X_all (just features: 10 rows) is \n {X_all[:10,:]}")
print(f"y_all (just petallen)   is \n {y_all}") 

+++ Start of regression experiments... +++

X_all (just features: 10 rows) is 
 [[4.6 3.6 1.  0. ]
 [4.3 3.  1.1 0. ]
 [5.  3.2 1.2 0. ]
 [5.8 4.  1.2 0. ]
 [4.4 3.  1.3 0. ]
 [4.4 3.2 1.3 0. ]
 [4.5 2.3 1.3 0. ]
 [4.7 3.2 1.3 0. ]
 [5.  3.5 1.3 0. ]
 [5.4 3.9 1.3 0. ]]
y_all (just petallen)   is 
 [0.2 0.1 0.2 0.2 0.2 0.2 0.3 0.2 0.3 0.4 0.2 0.2 0.3 0.2 0.1 0.3 0.2 0.2
 0.2 0.2 0.3 0.2 0.2 0.2 0.1 0.1 0.1 0.2 0.3 0.4 0.2 0.2 0.2 0.2 0.4 0.2
 0.2 0.2 0.4 0.6 0.2 0.5 0.4 0.2 0.3 0.2 0.4 1.4 1.  1.  1.  1.  1.3 1.
 1.1 1.4 1.1 1.2 1.3 1.3 1.2 1.  1.3 1.3 1.  1.3 1.2 1.5 1.3 1.2 1.3 1.4
 1.4 1.5 1.5 1.3 1.5 1.6 1.5 1.5 1.4 1.5 1.3 1.4 1.2 1.6 1.5 1.8 1.4 1.5
 1.5 1.7 1.6 1.7 1.8 1.8 2.  1.8 1.8 2.  1.5 1.9 2.4 1.9 1.8 1.5 2.  2.3
 2.  2.3 1.9 2.3 2.3 2.1 1.8 1.8 2.1 1.4 1.8 2.4 2.1 2.2 2.4 2.1 2.5 2.3
 2.2 1.8 1.6 2.3 2.1 1.8 2.5 1.9 2.3 1.8 2.  2.1 2.2 2.  2.3]


In [111]:
#
# we scramble the data, to give a different TRAIN/TEST split each time...
# 
indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_all = X_all[indices]              # we apply the _same_ permutation to each!
y_all = y_all[indices]              # again...
print("features\n", X_all[:10,:])
print("labels (petallen)\n",y_all)

features
 [[6.8 3.2 5.9 2. ]
 [5.6 3.  4.5 1. ]
 [5.  3.5 1.3 0. ]
 [6.4 3.2 5.3 2. ]
 [7.7 3.8 6.7 2. ]
 [6.2 3.4 5.4 2. ]
 [5.4 3.  4.5 1. ]
 [6.1 2.6 5.6 2. ]
 [6.9 3.1 5.1 2. ]
 [5.5 2.5 4.  1. ]]
labels (petallen)
 [2.3 1.5 0.3 2.3 2.2 2.3 1.5 1.4 2.3 1.3 2.1 1.3 0.2 2.4 1.3 1.7 1.8 1.8
 0.2 0.2 1.8 0.3 0.2 1.8 0.1 1.6 0.2 1.5 1.5 1.1 0.2 1.3 2.2 2.  2.1 0.3
 1.5 2.1 0.2 0.4 1.4 2.1 1.2 0.2 2.3 1.2 2.4 0.2 2.  0.4 1.3 1.4 1.6 2.
 0.2 0.1 0.2 0.4 1.5 0.1 2.2 2.1 1.8 0.2 1.8 1.4 1.9 0.2 1.6 1.  1.3 0.4
 1.  2.  2.3 2.4 1.1 0.2 1.5 1.  0.2 1.8 0.2 0.3 0.2 1.4 1.9 1.  0.2 1.3
 1.  0.2 1.9 0.2 2.5 1.8 1.  1.5 1.7 1.2 1.5 0.1 1.3 1.6 0.3 1.4 0.1 1.8
 0.6 1.2 0.2 1.5 0.2 2.3 0.3 1.3 2.1 0.3 0.4 0.5 2.3 1.4 2.5 0.2 2.  1.8
 0.2 1.  0.2 1.2 1.8 0.4 1.3 0.2 1.9 1.4 1.5 2.  0.2 1.8 1.5]


In [112]:
#
# We next separate into test data and training data ... 
#    + We will train on the training data...
#    + We will _not_ look at the testing data to build the model
#
# Then, afterward, we will test on the testing data -- and see how well we do!
#

#
# a common convention:  train on 80%, test on 20%    Let's define the TEST_PERCENT
#
NUM_ROWS = X_all.shape[0]     # the number of rows
TEST_PERCENT = 0.20
TEST_SIZE = int(TEST_PERCENT*NUM_ROWS)   # no harm in rounding down

X_test = X_all[:TEST_SIZE]    # first section are for testing
y_test = y_all[:TEST_SIZE]

X_train = X_all[TEST_SIZE:]   # all the rest are for training
y_train = y_all[TEST_SIZE:]

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows" )

training with 113 rows;  testing with 28 rows


In [113]:
print(f"y_test is {y_test}")
print(f"y_train is {y_train}")   # to "get a visual" on these...
# print(X_test)
# print(X_train)

y_test is [2.3 1.5 0.3 2.3 2.2 2.3 1.5 1.4 2.3 1.3 2.1 1.3 0.2 2.4 1.3 1.7 1.8 1.8
 0.2 0.2 1.8 0.3 0.2 1.8 0.1 1.6 0.2 1.5]
y_train is [1.5 1.1 0.2 1.3 2.2 2.  2.1 0.3 1.5 2.1 0.2 0.4 1.4 2.1 1.2 0.2 2.3 1.2
 2.4 0.2 2.  0.4 1.3 1.4 1.6 2.  0.2 0.1 0.2 0.4 1.5 0.1 2.2 2.1 1.8 0.2
 1.8 1.4 1.9 0.2 1.6 1.  1.3 0.4 1.  2.  2.3 2.4 1.1 0.2 1.5 1.  0.2 1.8
 0.2 0.3 0.2 1.4 1.9 1.  0.2 1.3 1.  0.2 1.9 0.2 2.5 1.8 1.  1.5 1.7 1.2
 1.5 0.1 1.3 1.6 0.3 1.4 0.1 1.8 0.6 1.2 0.2 1.5 0.2 2.3 0.3 1.3 2.1 0.3
 0.4 0.5 2.3 1.4 2.5 0.2 2.  1.8 0.2 1.  0.2 1.2 1.8 0.4 1.3 0.2 1.9 1.4
 1.5 2.  0.2 1.8 1.5]


In [114]:
#
# for most NNets, it's important to keep the feature values in the -1-to-1 range
#    This is done through the "StandardScaler" in scikit-learn
# 
USE_SCALER = True   # this variable is important! It tracks if we need to use the scaler...

# we "train the scaler"  (computes the mean and standard deviation)
if USE_SCALER == True:
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    # Scale with the training data! ave becomes 0; stdev becomes 1
    scaler.fit(X_train)   
    
if USE_SCALER == True:    # if we're using the scaler, all inputs need to be scaled...
    X_train_scaled = scaler.transform(X_train) # scale!
    X_test_scaled = scaler.transform(X_test) # scale!
    print("USING the input scaler:\n")
else:
    X_train_scaled = X_train.copy()  # not using the scaler
    X_test_scaled = X_test.copy()  # not using the scaler
    print("NOT using the input scaler:\n")
    
y_train_scaled = y_train  # the predicted/desired labels are not scaled
y_test_scaled = y_test  # not using the scaler
    
# ascii_table(X_train_scaled,y_train_scaled)  # unweildy
print(f"X_train_scaled (first 5 rows): {X_train_scaled[:5,:]}")

USING the input scaler:

X_train_scaled (first 5 rows): [[ 0.05003112 -0.11230034  0.27444923  0.05513514]
 [-0.42109523 -1.52229346  0.0480787   0.05513514]
 [-0.06775047  2.23768821 -1.42332976 -1.19091895]
 [ 0.87450222 -0.34729919  0.50081976  0.05513514]
 [ 0.63893905 -0.58229805  1.06674609  1.30118922]]


In [115]:
from sklearn.neural_network import MLPRegressor

#
# Here's where you can change the number of hidden layers
# and number of neurons!
#
nn_regressor = MLPRegressor(hidden_layer_sizes=(10,10), max_iter=400, activation="tanh",
                    solver='sgd', verbose=False, shuffle=True,
                    random_state=None, # reproduceability!
                    learning_rate_init=.1, learning_rate = 'adaptive')

print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
nn_regressor.fit(X_train_scaled, y_train_scaled)
print("\n\n++++++++++  TRAINING:   end  +++++++++++++++\n\n")

print(f"The (sq) prediction error (the loss) is {nn_regressor.loss_}") 



++++++++++  TRAINING:  begin  +++++++++++++++




++++++++++  TRAINING:   end  +++++++++++++++


The (sq) prediction error (the loss) is 0.012638891574217543


In [116]:
#
# how did it do? now we're making progress (by regressing)
#

def ascii_table_for_regressor(X,y,nn):
    """ a table including predictions using nn.predict """
    predictions = nn.predict(X) # all predictions
    # measure error
    error = 0.0
    # printing
    print(f"{'input ':>18s} ->  {'pred':^6s}  {'desr':^6s}  {'absdiff':^10s}") 
    for i in range(len(y)):
        pred = predictions[i]
        desired = y[i]
        result = abs(desired - pred)
        error += result
        # of use X_train to see the unscaled...
        print(f"{X_train[i,:]!s:>18s} ->  {pred:<+6.3f}  {desired:<+6.3f}  {result:^10.3f}") 
    print(f"\naverage abs error: {error/len(y)}")
    


#
# let's see how it did on the test data (also the training data!)
#
ascii_table_for_regressor(X_test_scaled,
                          y_test_scaled,
                          nn_regressor)   # this is our own f'n, above
#
# other things...
#
nn = nn_regressor  # less to type?
print("\n\n+++++ parameters, weights, etc. +++++\n")
print(f"\nweights/coefficients:\n")
for wts in nn.coefs_:
    print(wts)
print(f"\nintercepts: {nn.intercepts_}")
print(f"\nall parameters: {nn.get_params()}")

            input  ->   pred    desr    absdiff  
 [5.9 3.  4.2 1. ] ->  +2.162  +2.300    0.138   
 [5.5 2.4 3.8 1. ] ->  +1.388  +1.500    0.112   
 [5.8 4.  1.2 0. ] ->  +0.220  +0.300    0.080   
 [6.6 2.9 4.6 1. ] ->  +2.102  +2.300    0.198   
 [6.4 2.8 5.6 2. ] ->  +2.222  +2.200    0.022   
 [7.7 2.8 6.7 2. ] ->  +2.134  +2.300    0.166   
 [6.7 3.3 5.7 2. ] ->  +1.381  +1.500    0.119   
 [4.8 3.  1.4 0. ] ->  +2.005  +1.400    0.605   
 [6.2 2.2 4.5 1. ] ->  +2.036  +2.300    0.264   
 [6.9 3.1 5.4 2. ] ->  +1.212  +1.300    0.088   
 [5.5 3.5 1.3 0. ] ->  +2.072  +2.100    0.028   
 [5.1 3.8 1.9 0. ] ->  +1.300  +1.300    0.000   
 [6.1 2.9 4.7 1. ] ->  +0.248  +0.200    0.048   
 [7.6 3.  6.6 2. ] ->  +2.116  +2.400    0.284   
 [5.5 2.6 4.4 1. ] ->  +1.214  +1.300    0.086   
 [5.3 3.7 1.5 0. ] ->  +1.683  +1.700    0.017   
 [6.9 3.2 5.7 2. ] ->  +1.913  +1.800    0.113   
 [6.1 2.8 4.7 1. ] ->  +1.907  +1.800    0.107   
 [5.8 2.8 5.1 2. ] ->  +0.218  +0.200    0.018   


In [ ]:
"""
Your task!

Just as above, find the average abs. error in the other three botanical features:
  + sepalwid
  + sepallen
  + petalwid
  + above is petallen, with a ~0.14 av. abs. error per petal! (pretty good :-)
  
Feel free to copy-and-paste a lot! 
  + You will feel like regressing is second nature (not a bad thing!)
  
_Or_, run a loop over the columns... (see the concatenate call, above)
  + When you use concatenate, be sure all are slices, not single columns
  
Then, include a text (or markdown) cell with the four av. abs. errors
  + Just as some features are more important than others,
  + so, too are some features more predictable than others...
  
Not required...  How much do different network-shapes matter here?

Not required... but also interesting:  
  You could drop the species columns (species is now a feature), 
  in order to inquire how much "value" knowing species adds 
  when predicting each botanical measurement...

"""

In [117]:
#Predicit Feature___sepallen

df_final

sepallen  sepalwid  petallen  petalwid  irisname
0         4.6       3.6       1.0       0.2         0
1         4.3       3.0       1.1       0.1         0
2         5.0       3.2       1.2       0.2         0
3         5.8       4.0       1.2       0.2         0
4         4.4       3.0       1.3       0.2         0
..        ...       ...       ...       ...       ...
136       7.9       3.8       6.4       2.0         2
137       7.6       3.0       6.6       2.1         2
138       7.7       3.8       6.7       2.2         2
139       7.7       2.8       6.7       2.0         2
140       7.7       2.6       6.9       2.3         2

[141 rows x 5 columns]

In [119]:
A = df_final.values    
# print(A)

A = A.astype('float64') 
print(A)

NUM_ROWS, NUM_COLS = A.shape
print(f"\nThe dataset has {NUM_ROWS} rows and {NUM_COLS} cols")


[[4.6 3.6 1.  0.2 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [4.6 3.2 1.4 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.8 3.  1.4 0.3 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.  3.3 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.3 3.7 1.5 0.2 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.  3.5 1.6 0.6 0. ]
 [5.1 3.8 1.6 0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [5.4 3.4 1

In [120]:
print("+++ Start of regression experiments... +++\n")

X_all = A[:,1:].copy()  # columns 1, 2, 3, and 4
y_all = A[:,0].copy()            # y (labels) ... is all rows, column 0 (sepallen) only

print(f"X_all (just features: 10 rows) is \n {X_all[:10,:]}")
print(f"y_all (just petallen)   is \n {y_all}")


+++ Start of regression experiments... +++

X_all (just features: 10 rows) is 
 [[3.6 1.  0.2 0. ]
 [3.  1.1 0.1 0. ]
 [3.2 1.2 0.2 0. ]
 [4.  1.2 0.2 0. ]
 [3.  1.3 0.2 0. ]
 [3.2 1.3 0.2 0. ]
 [2.3 1.3 0.3 0. ]
 [3.2 1.3 0.2 0. ]
 [3.5 1.3 0.3 0. ]
 [3.9 1.3 0.4 0. ]]
y_all (just petallen)   is 
 [4.6 4.3 5.  5.8 4.4 4.4 4.5 4.7 5.  5.4 5.5 4.4 4.6 4.6 4.8 4.8 4.9 5.
 5.  5.1 5.1 5.2 5.5 4.6 4.9 4.9 4.9 5.  5.1 5.1 5.1 5.2 5.3 5.4 5.7 4.7
 4.8 5.  5.  5.  5.1 5.1 5.4 5.4 5.7 4.8 5.1 7.  4.9 5.  5.  5.7 5.6 5.5
 5.5 5.2 5.6 5.8 5.5 5.5 5.8 6.  6.1 5.6 5.8 5.6 5.7 5.9 6.4 5.5 6.3 6.6
 6.7 5.4 5.6 5.7 6.  6.  6.2 6.4 6.1 6.5 6.6 6.1 6.1 6.3 6.7 5.9 6.8 6.3
 6.9 6.7 6.  4.9 6.  6.2 5.6 6.1 6.3 5.7 6.  6.3 5.8 5.8 5.9 6.3 6.5 6.9
 6.5 6.7 6.4 6.4 6.2 6.9 6.4 6.5 6.8 6.1 6.3 6.3 6.4 6.4 6.7 6.7 6.7 6.9
 6.5 6.7 7.2 6.8 7.1 7.2 7.2 7.4 7.7 7.3 7.9 7.6 7.7 7.7 7.7]


In [121]:
# we scramble the data, to give a different TRAIN/TEST split each time...

indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_all = X_all[indices]              # we apply the _same_ permutation to each!
y_all = y_all[indices]              # again...
print("features\n", X_all[:10,:])
print("labels (petallen)\n",y_all)


features
 [[3.7 1.5 0.2 0. ]
 [3.  4.2 1.5 1. ]
 [3.1 1.5 0.1 0. ]
 [3.8 6.7 2.2 2. ]
 [2.7 4.1 1.  1. ]
 [2.3 4.  1.3 1. ]
 [2.9 4.7 1.4 1. ]
 [4.2 1.4 0.2 0. ]
 [2.6 4.4 1.2 1. ]
 [3.  5.  1.7 1. ]]
labels (petallen)
 [5.3 5.9 4.9 7.7 5.8 5.5 6.1 5.5 5.5 6.7 6.9 6.5 5.7 5.1 5.7 5.6 5.6 5.4
 6.4 5.5 5.1 4.8 6.4 5.1 5.8 6.  6.  4.9 4.4 7.7 5.  5.9 6.5 4.9 7.1 5.
 5.5 6.3 6.3 6.3 4.6 7.9 5.1 7.3 6.7 4.3 6.7 5.6 6.  6.9 4.4 5.8 6.4 6.2
 4.8 5.7 4.6 5.1 6.3 4.5 6.3 5.2 6.4 6.5 7.2 6.3 5.1 5.8 7.7 7.4 6.8 6.
 6.7 6.6 6.3 5.7 5.6 7.  6.7 4.6 5.7 5.  6.7 5.8 5.8 7.7 5.  6.9 6.7 6.2
 5.1 5.6 5.  5.  6.1 6.5 4.7 6.  4.8 7.6 5.2 5.2 6.2 6.7 5.  4.7 4.6 5.7
 4.9 6.  5.  4.9 6.1 5.5 6.6 6.8 5.  4.4 5.9 5.4 6.9 5.4 5.6 6.8 6.1 5.4
 7.2 6.1 6.3 6.4 5.1 6.4 5.  5.5 6.5 4.8 4.9 5.4 7.2 6.1 6.4]


In [122]:
#
# a common convention:  train on 80%, test on 20%    Let's define the TEST_PERCENT
#
NUM_ROWS = X_all.shape[0]     # the number of rows
TEST_PERCENT = 0.20
TEST_SIZE = int(TEST_PERCENT*NUM_ROWS)   # no harm in rounding down

X_test = X_all[:TEST_SIZE]    # first section are for testing
y_test = y_all[:TEST_SIZE]

X_train = X_all[TEST_SIZE:]   # all the rest are for training
y_train = y_all[TEST_SIZE:]

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows" )

print(f"y_test is {y_test}")
print(f"y_train is {y_train}")   # to "get a visual" on these...
# print(X_test)
# print(X_train)


training with 113 rows;  testing with 28 rows
y_test is [5.3 5.9 4.9 7.7 5.8 5.5 6.1 5.5 5.5 6.7 6.9 6.5 5.7 5.1 5.7 5.6 5.6 5.4
 6.4 5.5 5.1 4.8 6.4 5.1 5.8 6.  6.  4.9]
y_train is [4.4 7.7 5.  5.9 6.5 4.9 7.1 5.  5.5 6.3 6.3 6.3 4.6 7.9 5.1 7.3 6.7 4.3
 6.7 5.6 6.  6.9 4.4 5.8 6.4 6.2 4.8 5.7 4.6 5.1 6.3 4.5 6.3 5.2 6.4 6.5
 7.2 6.3 5.1 5.8 7.7 7.4 6.8 6.  6.7 6.6 6.3 5.7 5.6 7.  6.7 4.6 5.7 5.
 6.7 5.8 5.8 7.7 5.  6.9 6.7 6.2 5.1 5.6 5.  5.  6.1 6.5 4.7 6.  4.8 7.6
 5.2 5.2 6.2 6.7 5.  4.7 4.6 5.7 4.9 6.  5.  4.9 6.1 5.5 6.6 6.8 5.  4.4
 5.9 5.4 6.9 5.4 5.6 6.8 6.1 5.4 7.2 6.1 6.3 6.4 5.1 6.4 5.  5.5 6.5 4.8
 4.9 5.4 7.2 6.1 6.4]


In [123]:
# for most NNets, it's important to keep the feature values in the -1-to-1 range
#    This is done through the "StandardScaler" in scikit-learn
# 
USE_SCALER = True   # this variable is important! It tracks if we need to use the scaler...

# we "train the scaler"  (computes the mean and standard deviation)
if USE_SCALER == True:
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    # Scale with the training data! ave becomes 0; stdev becomes 1
    scaler.fit(X_train)   
    
if USE_SCALER == True:    # if we're using the scaler, all inputs need to be scaled...
    X_train_scaled = scaler.transform(X_train) # scale!
    X_test_scaled = scaler.transform(X_test) # scale!
    print("USING the input scaler:\n")
else:
    X_train_scaled = X_train.copy()  # not using the scaler
    X_test_scaled = X_test.copy()  # not using the scaler
    print("NOT using the input scaler:\n")
    
y_train_scaled = y_train  # the predicted/desired labels are not scaled
y_test_scaled = y_test  # not using the scaler
    
# ascii_table(X_train_scaled,y_train_scaled)  # unweildy
print(f"X_train_scaled (first 5 rows): {X_train_scaled[:5,:]}")



USING the input scaler:

X_train_scaled (first 5 rows): [[ 0.34360642 -1.3540539  -1.29014164 -1.21308122]
 [-0.12989999  1.2792872   1.40010978  1.15033564]
 [ 1.05386603 -1.3540539  -1.16203443 -1.21308122]
 [-0.12989999  0.73067448  0.75957372  1.15033564]
 [-0.12989999  0.95011957  0.75957372  1.15033564]]


In [125]:
from sklearn.neural_network import MLPRegressor

#
# Here's where you can change the number of hidden layers
# and number of neurons!
#
nn_regressor = MLPRegressor(hidden_layer_sizes=(10,10), max_iter=400, activation="tanh",
                    solver='sgd', verbose=False, shuffle=True,
                    random_state=None, # reproduceability!
                    learning_rate_init=.1, learning_rate = 'adaptive')

print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
nn_regressor.fit(X_train_scaled, y_train_scaled)
print("\n\n++++++++++  TRAINING:   end  +++++++++++++++\n\n")

print(f"The (sq) prediction error (the loss) is {nn_regressor.loss_}")




++++++++++  TRAINING:  begin  +++++++++++++++




++++++++++  TRAINING:   end  +++++++++++++++


The (sq) prediction error (the loss) is 0.03887807016517819


In [126]:
# how did it do? now we're making progress (by regressing)
#

def ascii_table_for_regressor(X,y,nn):
    """ a table including predictions using nn.predict """
    predictions = nn.predict(X) # all predictions
    # measure error
    error = 0.0
    # printing
    print(f"{'input ':>18s} ->  {'pred':^6s}  {'desr':^6s}  {'absdiff':^10s}") 
    for i in range(len(y)):
        pred = predictions[i]
        desired = y[i]
        result = abs(desired - pred)
        error += result
        # of use X_train to see the unscaled...
        print(f"{X_train[i,:]!s:>18s} ->  {pred:<+6.3f}  {desired:<+6.3f}  {result:^10.3f}") 
    print(f"\naverage abs error: {error/len(y)}")
    


In [127]:
# let's see how it did on the test data (also the training data!)
#
ascii_table_for_regressor(X_test_scaled,
                          y_test_scaled,
                          nn_regressor)   # this is our own f'n, above
#
# other things...
#
nn = nn_regressor  # less to type?
print("\n\n+++++ parameters, weights, etc. +++++\n")
print(f"\nweights/coefficients:\n")
for wts in nn.coefs_:
    print(wts)
print(f"\nintercepts: {nn.intercepts_}")
print(f"\nall parameters: {nn.get_params()}")



            input  ->   pred    desr    absdiff  
 [3.2 1.3 0.2 0. ] ->  +5.300  +5.300    0.000   
 [3.  6.1 2.3 2. ] ->  +6.017  +5.900    0.117   
 [3.5 1.3 0.3 0. ] ->  +4.718  +4.900    0.182   
 [3.  5.1 1.8 2. ] ->  +7.872  +7.700    0.172   
 [3.  5.5 1.8 2. ] ->  +5.778  +5.800    0.022   
 [3.1 1.5 0.1 0. ] ->  +5.668  +5.500    0.168   
 [3.  5.9 2.1 2. ] ->  +6.461  +6.100    0.361   
 [2.3 3.3 1.  1. ] ->  +5.591  +5.500    0.091   
 [2.4 3.8 1.1 1. ] ->  +6.157  +5.500    0.657   
 [3.3 4.7 1.6 1. ] ->  +6.654  +6.700    0.046   
 [3.4 5.6 2.4 2. ] ->  +6.755  +6.900    0.145   
 [2.9 5.6 1.8 2. ] ->  +6.821  +6.500    0.321   
 [3.2 1.4 0.2 0. ] ->  +6.262  +5.700    0.562   
 [3.8 6.4 2.  2. ] ->  +5.401  +5.100    0.301   
 [3.8 1.5 0.3 0. ] ->  +5.883  +5.700    0.183   
 [2.9 6.3 1.8 2. ] ->  +5.277  +5.600    0.323   
 [3.1 5.6 2.4 2. ] ->  +5.546  +5.600    0.054   
 [3.  1.1 0.1 0. ] ->  +6.276  +5.400    0.876   
 [2.5 5.8 1.8 2. ] ->  +6.225  +6.400    0.175   


In [129]:
#Predicit Feature___sepalwid

df_final

sepallen  sepalwid  petallen  petalwid  irisname
0         4.6       3.6       1.0       0.2         0
1         4.3       3.0       1.1       0.1         0
2         5.0       3.2       1.2       0.2         0
3         5.8       4.0       1.2       0.2         0
4         4.4       3.0       1.3       0.2         0
..        ...       ...       ...       ...       ...
136       7.9       3.8       6.4       2.0         2
137       7.6       3.0       6.6       2.1         2
138       7.7       3.8       6.7       2.2         2
139       7.7       2.8       6.7       2.0         2
140       7.7       2.6       6.9       2.3         2

[141 rows x 5 columns]

In [130]:
A = df_final.values    
# print(A)

A = A.astype('float64') 
print(A)

NUM_ROWS, NUM_COLS = A.shape
print(f"\nThe dataset has {NUM_ROWS} rows and {NUM_COLS} cols")

[[4.6 3.6 1.  0.2 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [4.6 3.2 1.4 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.8 3.  1.4 0.3 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.  3.3 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.3 3.7 1.5 0.2 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.  3.5 1.6 0.6 0. ]
 [5.1 3.8 1.6 0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [5.4 3.4 1

In [131]:
print("+++ Start of regression experiments... +++\n")

X_all = np.concatenate( (A[:,0:1], A[:,2:]),axis=1)  # columns 0, 2, 3, and 4
y_all = A[:,1]             # y (labels) ... is all rows, column 1 (petalwid) only

print(f"X_all (just features: 10 rows) is \n {X_all[:10,:]}")
print(f"y_all (just petallen)   is \n {y_all}")


+++ Start of regression experiments... +++

X_all (just features: 10 rows) is 
 [[4.6 1.  0.2 0. ]
 [4.3 1.1 0.1 0. ]
 [5.  1.2 0.2 0. ]
 [5.8 1.2 0.2 0. ]
 [4.4 1.3 0.2 0. ]
 [4.4 1.3 0.2 0. ]
 [4.5 1.3 0.3 0. ]
 [4.7 1.3 0.2 0. ]
 [5.  1.3 0.3 0. ]
 [5.4 1.3 0.4 0. ]]
y_all (just petallen)   is 
 [3.6 3.  3.2 4.  3.  3.2 2.3 3.2 3.5 3.9 3.5 2.9 3.4 3.2 3.  3.  3.  3.6
 3.3 3.5 3.5 3.4 4.2 3.1 3.1 3.1 3.1 3.4 3.8 3.7 3.4 3.5 3.7 3.7 4.4 3.2
 3.4 3.  3.4 3.5 3.8 3.3 3.9 3.4 3.8 3.4 3.8 3.2 2.4 2.3 2.  2.6 2.9 2.4
 2.4 2.7 2.5 2.7 2.3 2.5 2.6 2.2 2.8 3.  2.7 2.7 3.  3.  2.9 2.6 2.3 3.
 3.1 3.  3.  2.8 2.9 3.4 2.2 3.2 3.  2.8 2.9 2.9 2.8 3.3 3.1 3.2 2.8 2.5
 3.1 3.  2.7 2.5 3.  2.8 2.8 3.  2.7 2.5 2.2 2.5 2.8 2.7 3.  2.8 3.2 3.1
 3.  3.  2.7 3.2 3.4 3.1 3.1 3.  3.  2.6 2.9 3.4 2.8 2.8 3.1 3.3 3.3 3.2
 3.  2.5 3.  3.2 3.  3.2 3.6 2.8 3.  2.9 3.8 3.  3.8 2.8 2.6]


In [132]:
indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_all = X_all[indices]              # we apply the _same_ permutation to each!
y_all = y_all[indices]              # again...
print("features\n", X_all[:10,:])
print("labels (petallen)\n",y_all)



features
 [[5.1 1.5 0.3 0. ]
 [4.7 1.3 0.2 0. ]
 [4.8 1.6 0.2 0. ]
 [4.6 1.  0.2 0. ]
 [6.4 5.6 2.2 2. ]
 [5.6 4.2 1.3 1. ]
 [5.  1.5 0.2 0. ]
 [6.  5.  1.5 2. ]
 [4.6 1.4 0.2 0. ]
 [4.9 1.4 0.2 0. ]]
labels (petallen)
 [3.8 3.2 3.4 3.6 2.8 2.7 3.4 2.2 3.2 3.  3.  3.8 2.7 4.  3.  2.  3.5 3.3
 3.  3.5 3.4 2.6 3.2 2.9 2.7 2.5 3.7 3.7 2.8 2.7 2.3 3.5 3.8 3.4 3.1 3.4
 3.  3.4 3.1 3.6 3.4 2.9 3.  3.2 3.1 3.2 3.  3.2 2.2 2.7 2.6 3.3 3.  3.4
 2.5 3.  3.7 3.1 2.8 2.5 3.  2.3 3.  2.9 3.  2.3 3.8 2.7 2.7 3.2 3.4 3.6
 2.8 3.2 2.5 2.2 3.  3.4 3.9 2.8 2.8 3.  3.1 3.5 2.4 3.  3.  2.7 2.9 3.
 2.8 3.  2.8 2.8 3.1 3.4 3.2 3.1 2.3 3.2 3.1 3.5 3.5 2.8 3.  3.1 2.8 3.
 3.3 2.9 3.2 2.4 3.1 3.3 2.4 3.2 3.8 2.5 3.  3.  2.9 2.8 2.5 3.  3.  3.3
 2.6 2.5 3.9 3.2 3.1 2.8 3.  4.2 3.  4.4 2.9 2.9 2.6 3.8 2.6]


In [133]:
# a common convention:  train on 80%, test on 20%    Let's define the TEST_PERCENT
#
NUM_ROWS = X_all.shape[0]     # the number of rows
TEST_PERCENT = 0.20
TEST_SIZE = int(TEST_PERCENT*NUM_ROWS)   # no harm in rounding down

X_test = X_all[:TEST_SIZE]    # first section are for testing
y_test = y_all[:TEST_SIZE]

X_train = X_all[TEST_SIZE:]   # all the rest are for training
y_train = y_all[TEST_SIZE:]

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows" )

print(f"y_test is {y_test}")
print(f"y_train is {y_train}")   # to "get a visual" on these...
# print(X_test)
# print(X_train)



training with 113 rows;  testing with 28 rows
y_test is [3.8 3.2 3.4 3.6 2.8 2.7 3.4 2.2 3.2 3.  3.  3.8 2.7 4.  3.  2.  3.5 3.3
 3.  3.5 3.4 2.6 3.2 2.9 2.7 2.5 3.7 3.7]
y_train is [2.8 2.7 2.3 3.5 3.8 3.4 3.1 3.4 3.  3.4 3.1 3.6 3.4 2.9 3.  3.2 3.1 3.2
 3.  3.2 2.2 2.7 2.6 3.3 3.  3.4 2.5 3.  3.7 3.1 2.8 2.5 3.  2.3 3.  2.9
 3.  2.3 3.8 2.7 2.7 3.2 3.4 3.6 2.8 3.2 2.5 2.2 3.  3.4 3.9 2.8 2.8 3.
 3.1 3.5 2.4 3.  3.  2.7 2.9 3.  2.8 3.  2.8 2.8 3.1 3.4 3.2 3.1 2.3 3.2
 3.1 3.5 3.5 2.8 3.  3.1 2.8 3.  3.3 2.9 3.2 2.4 3.1 3.3 2.4 3.2 3.8 2.5
 3.  3.  2.9 2.8 2.5 3.  3.  3.3 2.6 2.5 3.9 3.2 3.1 2.8 3.  4.2 3.  4.4
 2.9 2.9 2.6 3.8 2.6]


In [134]:
# for most NNets, it's important to keep the feature values in the -1-to-1 range
#    This is done through the "StandardScaler" in scikit-learn
# 
USE_SCALER = True   # this variable is important! It tracks if we need to use the scaler...

# we "train the scaler"  (computes the mean and standard deviation)
if USE_SCALER == True:
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    # Scale with the training data! ave becomes 0; stdev becomes 1
    scaler.fit(X_train)   
    
if USE_SCALER == True:    # if we're using the scaler, all inputs need to be scaled...
    X_train_scaled = scaler.transform(X_train) # scale!
    X_test_scaled = scaler.transform(X_test) # scale!
    print("USING the input scaler:\n")
else:
    X_train_scaled = X_train.copy()  # not using the scaler
    X_test_scaled = X_test.copy()  # not using the scaler
    print("NOT using the input scaler:\n")
    
y_train_scaled = y_train  # the predicted/desired labels are not scaled
y_test_scaled = y_test  # not using the scaler
    
# ascii_table(X_train_scaled,y_train_scaled)  # unweildy
print(f"X_train_scaled (first 5 rows): {X_train_scaled[:5,:]}")


USING the input scaler:

X_train_scaled (first 5 rows): [[ 0.97986746  0.47658613  0.15564255 -0.11001639]
 [ 0.51168555  0.76581402  0.82692531  1.13316885]
 [-0.54172377  0.01382151  0.021386   -0.11001639]
 [-0.54172377 -1.54800909 -1.45543607 -1.35320164]
 [-1.00990568 -1.20093562 -1.18692297 -1.35320164]]


In [135]:
from sklearn.neural_network import MLPRegressor

#
# Here's where you can change the number of hidden layers
# and number of neurons!
#
nn_regressor = MLPRegressor(hidden_layer_sizes=(10,10), max_iter=400, activation="tanh",
                    solver='sgd', verbose=False, shuffle=True,
                    random_state=None, # reproduceability!
                    learning_rate_init=.1, learning_rate = 'adaptive')

print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
nn_regressor.fit(X_train_scaled, y_train_scaled)
print("\n\n++++++++++  TRAINING:   end  +++++++++++++++\n\n")

print(f"The (sq) prediction error (the loss) is {nn_regressor.loss_}")




++++++++++  TRAINING:  begin  +++++++++++++++




++++++++++  TRAINING:   end  +++++++++++++++


The (sq) prediction error (the loss) is 0.029531407080073156


In [136]:
def ascii_table_for_regressor(X,y,nn):
    """ a table including predictions using nn.predict """
    predictions = nn.predict(X) # all predictions
    # measure error
    error = 0.0
    # printing
    print(f"{'input ':>18s} ->  {'pred':^6s}  {'desr':^6s}  {'absdiff':^10s}") 
    for i in range(len(y)):
        pred = predictions[i]
        desired = y[i]
        result = abs(desired - pred)
        error += result
        # of use X_train to see the unscaled...
        print(f"{X_train[i,:]!s:>18s} ->  {pred:<+6.3f}  {desired:<+6.3f}  {result:^10.3f}") 
    print(f"\naverage abs error: {error/len(y)}")


In [137]:
# let's see how it did on the test data (also the training data!)
#
ascii_table_for_regressor(X_test_scaled,
                          y_test_scaled,
                          nn_regressor)   # this is our own f'n, above
#
# other things...
#
nn = nn_regressor  # less to type?
print("\n\n+++++ parameters, weights, etc. +++++\n")
print(f"\nweights/coefficients:\n")
for wts in nn.coefs_:
    print(wts)
print(f"\nintercepts: {nn.intercepts_}")
print(f"\nall parameters: {nn.get_params()}")


            input  ->   pred    desr    absdiff  
 [6.8 4.8 1.4 1. ] ->  +3.479  +3.800    0.321   
 [6.4 5.3 1.9 2. ] ->  +3.121  +3.200    0.079   
 [5.5 4.  1.3 1. ] ->  +3.199  +3.400    0.201   
 [5.5 1.3 0.2 0. ] ->  +3.048  +3.600    0.552   
 [5.1 1.9 0.4 0. ] ->  +3.106  +2.800    0.306   
 [5.1 1.5 0.2 0. ] ->  +2.657  +2.700    0.043   
 [4.9 1.5 0.1 0. ] ->  +3.338  +3.400    0.062   
 [6.2 5.4 2.3 2. ] ->  +2.571  +2.200    0.371   
 [4.4 1.3 0.2 0. ] ->  +3.064  +3.200    0.136   
 [4.6 1.4 0.3 0. ] ->  +3.262  +3.000    0.262   
 [6.7 4.7 1.5 1. ] ->  +3.090  +3.000    0.090   
 [5.  1.4 0.2 0. ] ->  +3.417  +3.800    0.383   
 [6.  4.5 1.6 1. ] ->  +2.916  +2.700    0.216   
 [6.3 5.6 1.8 2. ] ->  +4.057  +4.000    0.057   
 [5.7 4.2 1.2 1. ] ->  +3.234  +3.000    0.234   
 [6.8 5.9 2.3 2. ] ->  +2.367  +2.000    0.367   
 [4.9 1.5 0.1 0. ] ->  +3.545  +3.500    0.045   
 [6.4 4.5 1.5 1. ] ->  +2.983  +3.300    0.317   
 [5.6 4.5 1.5 1. ] ->  +2.662  +3.000    0.338   


In [138]:
#Predicit Feature___petallen

df_final

sepallen  sepalwid  petallen  petalwid  irisname
0         4.6       3.6       1.0       0.2         0
1         4.3       3.0       1.1       0.1         0
2         5.0       3.2       1.2       0.2         0
3         5.8       4.0       1.2       0.2         0
4         4.4       3.0       1.3       0.2         0
..        ...       ...       ...       ...       ...
136       7.9       3.8       6.4       2.0         2
137       7.6       3.0       6.6       2.1         2
138       7.7       3.8       6.7       2.2         2
139       7.7       2.8       6.7       2.0         2
140       7.7       2.6       6.9       2.3         2

[141 rows x 5 columns]

In [139]:
A = df_final.values    
# print(A)

A = A.astype('float64') 
print(A)

NUM_ROWS, NUM_COLS = A.shape
print(f"\nThe dataset has {NUM_ROWS} rows and {NUM_COLS} cols")


[[4.6 3.6 1.  0.2 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [4.6 3.2 1.4 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.8 3.  1.4 0.3 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.  3.3 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.2 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.3 3.7 1.5 0.2 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.  3.5 1.6 0.6 0. ]
 [5.1 3.8 1.6 0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [5.4 3.4 1

In [140]:
print("+++ Start of regression experiments... +++\n")

X_all = np.concatenate( (A[:,0:2], A[:,3:]),axis=1)  # columns 0, 1, 3, and 4
y_all = A[:,2]             # y (labels) ... is all rows, column 2 (petalwid) only

print(f"X_all (just features: 10 rows) is \n {X_all[:10,:]}")
print(f"y_all (just petallen)   is \n {y_all}")


+++ Start of regression experiments... +++

X_all (just features: 10 rows) is 
 [[4.6 3.6 0.2 0. ]
 [4.3 3.  0.1 0. ]
 [5.  3.2 0.2 0. ]
 [5.8 4.  0.2 0. ]
 [4.4 3.  0.2 0. ]
 [4.4 3.2 0.2 0. ]
 [4.5 2.3 0.3 0. ]
 [4.7 3.2 0.2 0. ]
 [5.  3.5 0.3 0. ]
 [5.4 3.9 0.4 0. ]]
y_all (just petallen)   is 
 [1.  1.1 1.2 1.2 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.4 1.4 1.4 1.4 1.4 1.4 1.4
 1.4 1.4 1.4 1.4 1.4 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.6
 1.6 1.6 1.6 1.6 1.6 1.7 1.7 1.7 1.7 1.9 1.9 4.7 3.3 3.3 3.5 3.5 3.6 3.7
 3.8 3.9 3.9 3.9 4.  4.  4.  4.  4.  4.1 4.1 4.2 4.2 4.2 4.3 4.4 4.4 4.4
 4.4 4.5 4.5 4.5 4.5 4.5 4.5 4.5 4.6 4.6 4.6 4.7 4.7 4.7 4.7 4.8 4.8 4.9
 4.9 5.  5.1 4.5 4.8 4.8 4.9 4.9 4.9 5.  5.  5.  5.1 5.1 5.1 5.1 5.1 5.1
 5.2 5.2 5.3 5.3 5.4 5.4 5.5 5.5 5.5 5.6 5.6 5.6 5.6 5.6 5.6 5.7 5.7 5.7
 5.8 5.8 5.8 5.9 5.9 6.  6.1 6.1 6.1 6.3 6.4 6.6 6.7 6.7 6.9]


In [141]:
indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_all = X_all[indices]              # we apply the _same_ permutation to each!
y_all = y_all[indices]              # again...
print("features\n", X_all[:10,:])
print("labels (petallen)\n",y_all)



features
 [[6.4 2.8 2.1 2. ]
 [5.  3.6 0.2 0. ]
 [6.7 3.  2.3 2. ]
 [6.8 3.2 2.3 2. ]
 [4.9 2.5 1.7 2. ]
 [5.  3.5 0.3 0. ]
 [4.6 3.1 0.2 0. ]
 [6.1 3.  1.8 2. ]
 [6.  3.  1.8 2. ]
 [5.6 3.  1.3 1. ]]
labels (petallen)
 [5.6 1.4 5.2 5.9 4.5 1.3 1.5 4.9 4.8 4.1 4.7 6.  1.5 1.5 5.8 1.5 1.  1.5
 1.4 4.5 1.5 5.  4.2 5.  6.4 3.8 5.8 5.5 3.9 4.7 5.2 5.4 1.1 4.9 3.9 5.1
 1.5 4.3 1.3 1.7 5.1 4.6 1.2 5.6 5.6 5.1 3.3 4.5 4.2 5.1 4.9 5.6 5.7 4.6
 3.9 5.6 1.4 4.6 1.6 4.  6.9 1.3 1.3 1.7 6.7 4.5 5.5 1.3 1.4 4.1 1.9 1.4
 6.6 3.5 4.  4.7 5.5 6.3 4.5 5.7 4.5 5.8 4.8 5.1 1.6 4.  1.7 1.3 1.5 6.1
 3.6 1.4 5.6 1.6 6.1 6.1 5.  5.  1.9 1.6 4.8 4.  6.7 3.3 4.7 3.7 5.1 4.5
 5.1 5.9 1.3 4.9 1.6 1.5 5.3 1.4 4.  1.5 1.4 1.4 1.2 1.4 4.8 4.4 1.6 4.5
 4.9 4.2 1.5 1.4 5.3 5.7 1.7 4.4 4.4 4.4 1.4 5.4 3.5 4.7 1.5]


In [142]:
# a common convention:  train on 80%, test on 20%    Let's define the TEST_PERCENT
#
NUM_ROWS = X_all.shape[0]     # the number of rows
TEST_PERCENT = 0.20
TEST_SIZE = int(TEST_PERCENT*NUM_ROWS)   # no harm in rounding down

X_test = X_all[:TEST_SIZE]    # first section are for testing
y_test = y_all[:TEST_SIZE]

X_train = X_all[TEST_SIZE:]   # all the rest are for training
y_train = y_all[TEST_SIZE:]

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows" )

print(f"y_test is {y_test}")
print(f"y_train is {y_train}")   # to "get a visual" on these...
# print(X_test)
# print(X_train)



training with 113 rows;  testing with 28 rows
y_test is [5.6 1.4 5.2 5.9 4.5 1.3 1.5 4.9 4.8 4.1 4.7 6.  1.5 1.5 5.8 1.5 1.  1.5
 1.4 4.5 1.5 5.  4.2 5.  6.4 3.8 5.8 5.5]
y_train is [3.9 4.7 5.2 5.4 1.1 4.9 3.9 5.1 1.5 4.3 1.3 1.7 5.1 4.6 1.2 5.6 5.6 5.1
 3.3 4.5 4.2 5.1 4.9 5.6 5.7 4.6 3.9 5.6 1.4 4.6 1.6 4.  6.9 1.3 1.3 1.7
 6.7 4.5 5.5 1.3 1.4 4.1 1.9 1.4 6.6 3.5 4.  4.7 5.5 6.3 4.5 5.7 4.5 5.8
 4.8 5.1 1.6 4.  1.7 1.3 1.5 6.1 3.6 1.4 5.6 1.6 6.1 6.1 5.  5.  1.9 1.6
 4.8 4.  6.7 3.3 4.7 3.7 5.1 4.5 5.1 5.9 1.3 4.9 1.6 1.5 5.3 1.4 4.  1.5
 1.4 1.4 1.2 1.4 4.8 4.4 1.6 4.5 4.9 4.2 1.5 1.4 5.3 5.7 1.7 4.4 4.4 4.4
 1.4 5.4 3.5 4.7 1.5]


In [143]:
# for most NNets, it's important to keep the feature values in the -1-to-1 range
#    This is done through the "StandardScaler" in scikit-learn
# 
USE_SCALER = True   # this variable is important! It tracks if we need to use the scaler...

# we "train the scaler"  (computes the mean and standard deviation)
if USE_SCALER == True:
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    # Scale with the training data! ave becomes 0; stdev becomes 1
    scaler.fit(X_train)   
    
if USE_SCALER == True:    # if we're using the scaler, all inputs need to be scaled...
    X_train_scaled = scaler.transform(X_train) # scale!
    X_test_scaled = scaler.transform(X_test) # scale!
    print("USING the input scaler:\n")
else:
    X_train_scaled = X_train.copy()  # not using the scaler
    X_test_scaled = X_test.copy()  # not using the scaler
    print("NOT using the input scaler:\n")
    
y_train_scaled = y_train  # the predicted/desired labels are not scaled
y_test_scaled = y_test  # not using the scaler
    
# ascii_table(X_train_scaled,y_train_scaled)  # unweildy
print(f"X_train_scaled (first 5 rows): {X_train_scaled[:5,:]}")


USING the input scaler:

X_train_scaled (first 5 rows): [[-0.07403773 -0.80753214 -0.00933928  0.02217846]
 [ 1.0016247   0.14300048  0.38641286  0.02217846]
 [ 0.7625886  -0.09463267  1.04599976  1.27526123]
 [ 1.24066079  0.14300048  1.17791714  1.27526123]
 [-1.86680844 -0.09463267 -1.46043047 -1.23090431]]


In [144]:
from sklearn.neural_network import MLPRegressor

#
# Here's where you can change the number of hidden layers
# and number of neurons!
#
nn_regressor = MLPRegressor(hidden_layer_sizes=(10,10), max_iter=400, activation="tanh",
                    solver='sgd', verbose=False, shuffle=True,
                    random_state=None, # reproduceability!
                    learning_rate_init=.1, learning_rate = 'adaptive')

print("\n\n++++++++++  TRAINING:  begin  +++++++++++++++\n\n")
nn_regressor.fit(X_train_scaled, y_train_scaled)
print("\n\n++++++++++  TRAINING:   end  +++++++++++++++\n\n")

print(f"The (sq) prediction error (the loss) is {nn_regressor.loss_}")




++++++++++  TRAINING:  begin  +++++++++++++++




++++++++++  TRAINING:   end  +++++++++++++++


The (sq) prediction error (the loss) is 0.04504380539067758


In [145]:
def ascii_table_for_regressor(X,y,nn):
    """ a table including predictions using nn.predict """
    predictions = nn.predict(X) # all predictions
    # measure error
    error = 0.0
    # printing
    print(f"{'input ':>18s} ->  {'pred':^6s}  {'desr':^6s}  {'absdiff':^10s}") 
    for i in range(len(y)):
        pred = predictions[i]
        desired = y[i]
        result = abs(desired - pred)
        error += result
        # of use X_train to see the unscaled...
        print(f"{X_train[i,:]!s:>18s} ->  {pred:<+6.3f}  {desired:<+6.3f}  {result:^10.3f}") 
    print(f"\naverage abs error: {error/len(y)}")
    


In [146]:
# let's see how it did on the test data (also the training data!)
#
ascii_table_for_regressor(X_test_scaled,
                          y_test_scaled,
                          nn_regressor)   # this is our own f'n, above
#
# other things...
#
nn = nn_regressor  # less to type?
print("\n\n+++++ parameters, weights, etc. +++++\n")
print(f"\nweights/coefficients:\n")
for wts in nn.coefs_:
    print(wts)
print(f"\nintercepts: {nn.intercepts_}")
print(f"\nall parameters: {nn.get_params()}")


            input  ->   pred    desr    absdiff  
 [5.8 2.7 1.2 1. ] ->  +5.628  +5.600    0.028   
 [6.7 3.1 1.5 1. ] ->  +1.446  +1.400    0.046   
 [6.5 3.  2.  2. ] ->  +5.874  +5.200    0.674   
 [6.9 3.1 2.1 2. ] ->  +5.868  +5.900    0.032   
 [4.3 3.  0.1 0. ] ->  +4.961  +4.500    0.461   
 [5.6 2.8 2.  2. ] ->  +1.439  +1.300    0.139   
 [5.6 2.5 1.1 1. ] ->  +1.457  +1.500    0.043   
 [6.9 3.1 2.3 2. ] ->  +5.316  +4.900    0.416   
 [5.1 3.7 0.4 0. ] ->  +5.254  +4.800    0.454   
 [6.4 2.9 1.3 1. ] ->  +3.925  +4.100    0.175   
 [5.5 3.5 0.2 0. ] ->  +4.554  +4.700    0.146   
 [5.4 3.9 0.4 0. ] ->  +5.960  +6.000    0.040   
 [5.8 2.7 1.9 2. ] ->  +1.453  +1.500    0.047   
 [6.6 2.9 1.3 1. ] ->  +1.471  +1.500    0.029   
 [5.  3.2 0.2 0. ] ->  +5.708  +5.800    0.092   
 [6.4 2.8 2.2 2. ] ->  +1.452  +1.500    0.048   
 [6.1 2.6 1.4 2. ] ->  +1.430  +1.000    0.430   
 [6.  2.7 1.6 1. ] ->  +1.471  +1.500    0.029   
 [4.9 2.4 1.  1. ] ->  +1.452  +1.400    0.052   
