In [122]:
#
# hw4pr3births:  birth classification by month + day    (above/below median: 190942)
#

In [123]:
#
# UPDATED for births...
#


#
# We don't need any data at all to create a predictive model!  190942 median births
#
import random

def predictive_model( Features ):
    """ input: a list of two features 
                [ month, day ]
        output: the predicted number of births, either
                 below median (0)  or above median (1)
    """
    [ month, day ] = Features # unpacking!
    if 6 <= month <= 9:
        return 'above median (1)'
    else:
        return 'below median (0)'
    
#
# Try it!
# 
# Features = eval(input("Enter new Features: "))
#
Features = [ 9, 6 ] # september 6       # only TWO features here!
result = predictive_model( Features )
print(f"I predict {result} from Features {Features}")

I predict above median (1) from Features [9, 6]


In [124]:
#
# (now, to explore how we _can_ use data to do better... :-) 
#

In [125]:
# libraries!
import numpy as np      # numpy is Python's "array" library
import pandas as pd     # Pandas is Python's "data" library ("dataframe" == spreadsheet)

In [126]:
#
# Notice that almost all of these cells are still for flowers!
#

#
# Your task is to adapt them to build a births-frequency model (above/below median)
#

In [127]:
# let's read in our flower data...
# 
# for read_csv, use header=0 when row 0 is a header row
# 
filename = 'births.csv'
df = pd.read_csv(filename, header=0)   # encoding="latin1" et al.
print(f"{filename} : file read into a pandas dataframe.")

births.csv : file read into a pandas dataframe.


In [128]:
#
# a dataframe is a "spreadsheet in Python"   (seems to have an extra column!)
#
pd.set_option('display.max_rows', 100)  # None for no limit; default: 10
pd.set_option('display.min_rows', 100)  # None for no limit; default: 10
# let's view it!
df

month  day  births above/below median  \
0        1    1  160369              below   
1        1    2  169896              below   
2        1    3  180036              below   
3        1    4  182854              below   
4        1    5  184145              below   
5        1    6  186726              below   
6        1    7  188277              below   
7        1    8  185186              below   
8        1    9  181511              below   
9        1   10  183668              below   
10       1   11  187006              below   
11       1   12  188032              below   
12       1   13  189202              below   
13       1   14  192648              above   
14       1   15  189346              below   
15       1   16  186601              below   
16       1   17  186186              below   
17       1   18  188293              below   
18       1   19  189261              below   
19       1   20  190701              below   
20       1   21  191610              above   
21       1   22  189712              below   
22       1   23  186670              below   
23       1   24  186128              below   
24       1   25  187920              below   
25       1   26  188636              below   
26       1   27  189881              below   
27       1   28  190872              below   
28       1   29  188092              below   
29       1   30  185769              below   
30       1   31  183931              below   
31       2    1  186458              below   
32       2    2  189721              below   
33       2    3  190473              below   
34       2    4  190433              below   
35       2    5  189132              below   
36       2    6  187124              below   
37       2    7  185986              below   
38       2    8  186741              below   
39       2    9  188543              below   
40       2   10  192034              above   
41       2   11  192632              above   
42       2   12  192948              above   
43       2   13  185576              below   
44       2   14  194510              above   
45       2   15  188253              below   
46       2   16  189281              below   
47       2   17  191707              above   
48       2   18  192839              above   
49       2   19  190064              below   
..     ...  ...     ...                ...   
322     11   13  189313              below   
323     11   14  191286              above   
324     11   15  190061              below   
325     11   16  190978              above   
326     11   17  193696              above   
327     11   18  194612              above   
328     11   19  193775              above   
329     11   20  192775              above   
330     11   21  192033              above   
331     11   22  184076              below   
332     11   23  186026              below   
333     11   24  185885              below   
334     11   25  185992              below   
335     11   26  183490              below   
336     11   27  180462              below   
337     11   28  183631              below   
338     11   29  187069              below   
339     11   30  190619              below   
340     11   31     215              below   
341     12    1  193460              above   
342     12    2  193212              above   
343     12    3  190340              below   
344     12    4  188749              below   
345     12    5  189387              below   
346     12    6  187322              below   
347     12    7  188173              below   
348     12    8  192152              above   
349     12    9  191753              above   
350     12   10  191413              above   
351     12   11  189540              below   
352     12   12  191652              above   
353     12   13  187067              below   
354     12   14  191684              above   
355     12   15  196832              above   
356     12   16  198724              above   
357

In [129]:
#
# let's look at our pandas dataframe   (Aargh: that extra column!)
#
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 5 columns):
 #   Column                                                   Non-Null Count  Dtype  
---  ------                                                   --------------  -----  
 0   month                                                    372 non-null    int64  
 1   day                                                      372 non-null    int64  
 2   births                                                   372 non-null    int64  
 3   above/below median                                       372 non-null    object 
 4   from http://chmullig.com/2012/06/births-by-day-of-year/  0 non-null      float64
dtypes: float64(1), int64(3), object(1)
memory usage: 14.7+ KB


In [130]:
#
# let's drop that last column (dropping is usually by _name_):
#
#   if you want a list of the column names use df.columns
df_clean = df.drop(columns=['births','from http://chmullig.com/2012/06/births-by-day-of-year/'],axis=1)  # drop by name is typical
df_clean.info()                         # should be happier!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   month               372 non-null    int64 
 1   day                 372 non-null    int64 
 2   above/below median  372 non-null    object
dtypes: int64(2), object(1)
memory usage: 8.8+ KB


In [131]:
#
# let's keep our column names in variables, for reference
#
COLUMNS = df_clean.columns            # "list" of columns
print(f"COLUMNS is {COLUMNS}\n")  
  # It's a "pandas" list, called an Index
  # use it just as a Python list of strings:
print(f"COLUMNS[0] is {COLUMNS[0]}\n")

# let's create a dictionary to look up any column index by name
COL_INDEX = {}
for i, name in enumerate(COLUMNS):
    COL_INDEX[name] = i  # using the name (as key), look up the value (i)
print(f"COL_INDEX is {COL_INDEX}")

COLUMNS is Index(['month', 'day', 'above/below median'], dtype='object')

COLUMNS[0] is month

COL_INDEX is {'month': 0, 'day': 1, 'above/below median': 2}


In [132]:
#
# let's look at our cleaned-up dataframe...
#
df_clean.info()   
#
# notice that the non-null is _different_ for irisname!
df_clean   # show a table! (the problem rows are the last two...)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   month               372 non-null    int64 
 1   day                 372 non-null    int64 
 2   above/below median  372 non-null    object
dtypes: int64(2), object(1)
memory usage: 8.8+ KB


month  day above/below median
0        1    1              below
1        1    2              below
2        1    3              below
3        1    4              below
4        1    5              below
5        1    6              below
6        1    7              below
7        1    8              below
8        1    9              below
9        1   10              below
10       1   11              below
11       1   12              below
12       1   13              below
13       1   14              above
14       1   15              below
15       1   16              below
16       1   17              below
17       1   18              below
18       1   19              below
19       1   20              below
20       1   21              above
21       1   22              below
22       1   23              below
23       1   24              below
24       1   25              below
25       1   26              below
26       1   27              below
27       1   28              below
28       1   29              below
29       1   30              below
30       1   31              below
31       2    1              below
32       2    2              below
33       2    3              below
34       2    4              below
35       2    5              below
36       2    6              below
37       2    7              below
38       2    8              below
39       2    9              below
40       2   10              above
41       2   11              above
42       2   12              above
43       2   13              below
44       2   14              above
45       2   15              below
46       2   16              below
47       2   17              above
48       2   18              above
49       2   19              below
..     ...  ...                ...
322     11   13              below
323     11   14              above
324     11   15              below
325     11   16              above
326     11   17              above
327     11   18              above
328     11   19              above
329     11   20              above
330     11   21              above
331     11   22              below
332     11   23              below
333     11   24              below
334     11   25              below
335     11   26              below
336     11   27              below
337     11   28              below
338     11   29              below
339     11   30              below
340     11   31              below
341     12    1              above
342     12    2              above
343     12    3              below
344     12    4              below
345     12    5              below
346     12    6              below
347     12    7              below
348     12    8              above
349     12    9              above
350     12   10              above
351     12   11              below
352     12   12              above
353     12   13              below
354     12   14              above
355     12   15              above
356     12   16              above
357     12   17              above
358     12   18              above
359     12   19              above
360     12   20              above
361     12   21              above
362     12   22              below
363     12   23              below
364     12   24              below
365     12   25              below
366     12   26              below
367     12   27              above
368     12   28              above
369     12   29              above
370     12   30              above
371     12   31              above

[372 rows x 3 columns]

In [133]:
#
# typically, after dropping columns we don't want, 
#   we drop rows with missing data (other approaches are possible, too)
#
df_full = df_clean.dropna()   # this removes all rows with nan items
df_full.info()                # it's "full" because it has no nan items
df_full
#
# notice that _all_ of the rows now have 142 non-null items
#    also, the last row isn't real data... we'll handle it next

<class 'pandas.core.frame.DataFrame'>
Int64Index: 372 entries, 0 to 371
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   month               372 non-null    int64 
 1   day                 372 non-null    int64 
 2   above/below median  372 non-null    object
dtypes: int64(2), object(1)
memory usage: 11.6+ KB


month  day above/below median
0        1    1              below
1        1    2              below
2        1    3              below
3        1    4              below
4        1    5              below
5        1    6              below
6        1    7              below
7        1    8              below
8        1    9              below
9        1   10              below
10       1   11              below
11       1   12              below
12       1   13              below
13       1   14              above
14       1   15              below
15       1   16              below
16       1   17              below
17       1   18              below
18       1   19              below
19       1   20              below
20       1   21              above
21       1   22              below
22       1   23              below
23       1   24              below
24       1   25              below
25       1   26              below
26       1   27              below
27       1   28              below
28       1   29              below
29       1   30              below
30       1   31              below
31       2    1              below
32       2    2              below
33       2    3              below
34       2    4              below
35       2    5              below
36       2    6              below
37       2    7              below
38       2    8              below
39       2    9              below
40       2   10              above
41       2   11              above
42       2   12              above
43       2   13              below
44       2   14              above
45       2   15              below
46       2   16              below
47       2   17              above
48       2   18              above
49       2   19              below
..     ...  ...                ...
322     11   13              below
323     11   14              above
324     11   15              below
325     11   16              above
326     11   17              above
327     11   18              above
328     11   19              above
329     11   20              above
330     11   21              above
331     11   22              below
332     11   23              below
333     11   24              below
334     11   25              below
335     11   26              below
336     11   27              below
337     11   28              below
338     11   29              below
339     11   30              below
340     11   31              below
341     12    1              above
342     12    2              above
343     12    3              below
344     12    4              below
345     12    5              below
346     12    6              below
347     12    7              below
348     12    8              above
349     12    9              above
350     12   10              above
351     12   11              below
352     12   12              above
353     12   13              below
354     12   14              above
355     12   15              above
356     12   16              above
357     12   17              above
358     12   18              above
359     12   19              above
360     12   20              above
361     12   21              above
362     12   22              below
363     12   23              below
364     12   24              below
365     12   25              below
366     12   26              below
367     12   27              above
368     12   28              above
369     12   29              above
370     12   30              above
371     12   31              above

[372 rows x 3 columns]

In [134]:
# 
# get rid of last row!
#
df_final = df_full.iloc[:]   # not the syntax I would choose
# careful:  don't run this again!
print(df_final.shape)
df_final

(372, 3)


month  day above/below median
0        1    1              below
1        1    2              below
2        1    3              below
3        1    4              below
4        1    5              below
5        1    6              below
6        1    7              below
7        1    8              below
8        1    9              below
9        1   10              below
10       1   11              below
11       1   12              below
12       1   13              below
13       1   14              above
14       1   15              below
15       1   16              below
16       1   17              below
17       1   18              below
18       1   19              below
19       1   20              below
20       1   21              above
21       1   22              below
22       1   23              below
23       1   24              below
24       1   25              below
25       1   26              below
26       1   27              below
27       1   28              below
28       1   29              below
29       1   30              below
30       1   31              below
31       2    1              below
32       2    2              below
33       2    3              below
34       2    4              below
35       2    5              below
36       2    6              below
37       2    7              below
38       2    8              below
39       2    9              below
40       2   10              above
41       2   11              above
42       2   12              above
43       2   13              below
44       2   14              above
45       2   15              below
46       2   16              below
47       2   17              above
48       2   18              above
49       2   19              below
..     ...  ...                ...
322     11   13              below
323     11   14              above
324     11   15              below
325     11   16              above
326     11   17              above
327     11   18              above
328     11   19              above
329     11   20              above
330     11   21              above
331     11   22              below
332     11   23              below
333     11   24              below
334     11   25              below
335     11   26              below
336     11   27              below
337     11   28              below
338     11   29              below
339     11   30              below
340     11   31              below
341     12    1              above
342     12    2              above
343     12    3              below
344     12    4              below
345     12    5              below
346     12    6              below
347     12    7              below
348     12    8              above
349     12    9              above
350     12   10              above
351     12   11              below
352     12   12              above
353     12   13              below
354     12   14              above
355     12   15              above
356     12   16              above
357     12   17              above
358     12   18              above
359     12   19              above
360     12   20              above
361     12   21              above
362     12   22              below
363     12   23              below
364     12   24              below
365     12   25              below
366     12   26              below
367     12   27              above
368     12   28              above
369     12   29              above
370     12   30              above
371     12   31              above

[372 rows x 3 columns]

In [135]:
#
# SEE BELOW for a cell updated for births (using median-checking!)
#

# all of scikit-learn's ML routines need numbers, not strings
#   ... even for categories/classifications (like species!)
#   so, we will convert the flower-species to numbers:

MEDIAN = ['below','above']   # int to str
MEDIAN_INDEX = {'below':0,'above':1,}  # str to int

def convert_species(medianname):
    """ return the species index (a unique integer/category) """
    #print(f"converting {speciesname}...")
    return MEDIAN_INDEX[medianname]

# Let's try it out...
for name in MEDIAN:
    print(f"{name} maps to {convert_species(name)}")

below maps to 0
above maps to 1


In [136]:
#
# we can "apply" to a whole column
#   it may give a warning, but this is ok...
#

df_final['above/below median'] = df_final['above/below median'].apply(convert_species)

# Don't run this twice!   Why?!  What's "KeyError: 0"?
#   (for sure, you can always go back and re-establish definitions)

# don't worry about the (possible)  "SettingWithCopyWarning" here...

In [137]:
#
# let's see it!  (this is safe to run many times...)
#
df_final         # print(df_final.tostring())  # for _all_ rows...

month  day  above/below median
0        1    1                   0
1        1    2                   0
2        1    3                   0
3        1    4                   0
4        1    5                   0
5        1    6                   0
6        1    7                   0
7        1    8                   0
8        1    9                   0
9        1   10                   0
10       1   11                   0
11       1   12                   0
12       1   13                   0
13       1   14                   1
14       1   15                   0
15       1   16                   0
16       1   17                   0
17       1   18                   0
18       1   19                   0
19       1   20                   0
20       1   21                   1
21       1   22                   0
22       1   23                   0
23       1   24                   0
24       1   25                   0
25       1   26                   0
26       1   27                   0
27       1   28                   0
28       1   29                   0
29       1   30                   0
30       1   31                   0
31       2    1                   0
32       2    2                   0
33       2    3                   0
34       2    4                   0
35       2    5                   0
36       2    6                   0
37       2    7                   0
38       2    8                   0
39       2    9                   0
40       2   10                   1
41       2   11                   1
42       2   12                   1
43       2   13                   0
44       2   14                   1
45       2   15                   0
46       2   16                   0
47       2   17                   1
48       2   18                   1
49       2   19                   0
..     ...  ...                 ...
322     11   13                   0
323     11   14                   1
324     11   15                   0
325     11   16                   1
326     11   17                   1
327     11   18                   1
328     11   19                   1
329     11   20                   1
330     11   21                   1
331     11   22                   0
332     11   23                   0
333     11   24                   0
334     11   25                   0
335     11   26                   0
336     11   27                   0
337     11   28                   0
338     11   29                   0
339     11   30                   0
340     11   31                   0
341     12    1                   1
342     12    2                   1
343     12    3                   0
344     12    4                   0
345     12    5                   0
346     12    6                   0
347     12    7                   0
348     12    8                   1
349     12    9                   1
350     12   10                   1
351     12   11                   0
352     12   12                   1
353     12   13                   0
354     12   14                   1
355     12   15                   1
356     12   16                   1
357     12   17                   1
358     12   18                   1
359     12   19                   1
360     12   20                   1
361     12   21                   1
362     12   22                   0
363     12   23                   0
364     12   24                   0
365     12   25                   0
366     12   26                   0
367     12   27                   1
368     12   28                   1
369     12   29                   1
370     12   30                   1
371     12   31                   1

[372 rows x 3 columns]

In [138]:
#
# let's convert our dataframe to a numpy array, named A
#    Our ML library, scikit-learn operates entirely on numpy arrays.
#
A = df_final.values    # .values gets the numpy array
print(A)

[[ 1  1  0]
 [ 1  2  0]
 [ 1  3  0]
 ...
 [12 29  1]
 [12 30  1]
 [12 31  1]]


In [139]:
#
# let's make sure it's all floating-point, so we can multiply and divide
#
A = A.astype('float64')  # so many:  www.tutorialspoint.com/numpy/numpy_data_types.htm
print(A)

[[ 1.  1.  0.]
 [ 1.  2.  0.]
 [ 1.  3.  0.]
 ...
 [12. 29.  1.]
 [12. 30.  1.]
 [12. 31.  1.]]


In [140]:
#
# nice to have NUM_ROWS and NUM_COLS around
#
NUM_ROWS, NUM_COLS = A.shape
print(f"\nThe dataset has {NUM_ROWS} rows and {NUM_COLS} cols")


The dataset has 372 rows and 3 cols


In [141]:
# let's use all of our variables, to reinforce names...

# choose a row index, n:
n = 368
print(f"flower #{n} is {A[n]}")

for i in range(len(COLUMNS)):
    colname = COLUMNS[i]
    if colname != 'above/below median':
        print(f"  Its {colname} is {A[n][i]}")
    else:
        species_num = int(A[n][i])
        species = MEDIAN[species_num]
        print(f"  Its {colname} is {species} ({species_num})")

flower #368 is [12. 28.  1.]
  Its month is 12.0
  Its day is 28.0
  Its above/below median is above (1)


In [142]:
#
# but, we don't have to write our own ... because
#
#     we want knn for any k!
#     we want an already-debugged algorithm!
#     we want to ask iris q'ns instead of implementation ones... (?)
#

In [143]:
print("+++ Start of data definitions +++\n")

X_all = A[:,0:2]  # X (features) ... is all rows, columns 0, 1, 2, 3
y_all = A[:,2]    # y (labels) ... is all rows, column 4 only

print(f"X_all (just features) is \n {X_all}")
print(f"y_all (just labels)   is \n {y_all}")

+++ Start of data definitions +++

X_all (just features) is 
 [[ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1. 10.]
 [ 1. 11.]
 [ 1. 12.]
 [ 1. 13.]
 [ 1. 14.]
 [ 1. 15.]
 [ 1. 16.]
 [ 1. 17.]
 [ 1. 18.]
 [ 1. 19.]
 [ 1. 20.]
 [ 1. 21.]
 [ 1. 22.]
 [ 1. 23.]
 [ 1. 24.]
 [ 1. 25.]
 [ 1. 26.]
 [ 1. 27.]
 [ 1. 28.]
 [ 1. 29.]
 [ 1. 30.]
 [ 1. 31.]
 [ 2.  1.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 2.  9.]
 [ 2. 10.]
 [ 2. 11.]
 [ 2. 12.]
 [ 2. 13.]
 [ 2. 14.]
 [ 2. 15.]
 [ 2. 16.]
 [ 2. 17.]
 [ 2. 18.]
 [ 2. 19.]
 [ 2. 20.]
 [ 2. 21.]
 [ 2. 22.]
 [ 2. 23.]
 [ 2. 24.]
 [ 2. 25.]
 [ 2. 26.]
 [ 2. 27.]
 [ 2. 28.]
 [ 2. 29.]
 [ 2. 30.]
 [ 2. 31.]
 [ 3.  1.]
 [ 3.  2.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 3. 10.]
 [ 3. 11.]
 [ 3. 12.]
 [ 3. 13.]
 [ 3. 14.]
 [ 3. 15.]
 [ 3. 16.]
 [ 3. 17.]
 [ 3. 18.]
 [ 3. 19.]
 [ 3. 20.]
 [ 3. 21.]
 [ 3. 22.]
 [ 3. 23.]
 [ 

In [144]:
#
# we scramble the data, to give a different TRAIN/TEST split each time...
# 
indices = np.random.permutation(len(y_all))  # indices is a permutation-list

# we scramble both X and y, necessarily with the same permutation
X_labeled = X_all[indices]              # we apply the _same_ permutation to each!
y_labeled = y_all[indices]              # again...
print(X_labeled)
print(y_labeled)

[[ 8. 12.]
 [ 5. 11.]
 [ 3. 20.]
 [ 6. 17.]
 [ 7.  9.]
 [ 7. 25.]
 [ 2. 23.]
 [11.  4.]
 [ 1.  7.]
 [12. 14.]
 [ 4. 31.]
 [ 4.  6.]
 [ 9. 18.]
 [12.  1.]
 [ 6.  8.]
 [ 8.  3.]
 [ 7. 11.]
 [ 6. 15.]
 [ 7. 10.]
 [ 1. 28.]
 [10.  2.]
 [ 1. 21.]
 [10. 11.]
 [ 4. 24.]
 [ 4.  8.]
 [ 6.  9.]
 [ 9. 22.]
 [11.  6.]
 [ 9. 24.]
 [ 5. 18.]
 [ 9. 20.]
 [ 7. 28.]
 [ 2. 28.]
 [ 5.  9.]
 [ 8.  8.]
 [ 5. 20.]
 [12. 27.]
 [ 1.  3.]
 [ 9. 21.]
 [10. 29.]
 [11. 13.]
 [11. 12.]
 [ 8. 10.]
 [ 9.  7.]
 [ 3.  9.]
 [ 5.  5.]
 [ 8.  1.]
 [ 6. 21.]
 [ 4.  1.]
 [ 6. 20.]
 [ 2. 10.]
 [ 7. 14.]
 [ 3. 23.]
 [ 2. 17.]
 [ 4. 12.]
 [ 8. 22.]
 [12. 20.]
 [ 7. 16.]
 [ 2.  2.]
 [ 8. 13.]
 [ 8.  5.]
 [12. 15.]
 [ 3.  3.]
 [ 3. 15.]
 [ 3. 27.]
 [ 1.  1.]
 [ 9.  3.]
 [ 6. 25.]
 [ 7. 30.]
 [ 8.  7.]
 [ 2. 26.]
 [ 4. 29.]
 [ 8. 30.]
 [12.  4.]
 [11.  3.]
 [10. 22.]
 [ 3.  5.]
 [ 4. 23.]
 [12. 10.]
 [ 6. 28.]
 [12.  6.]
 [ 1.  4.]
 [10. 16.]
 [ 6. 19.]
 [12.  9.]
 [ 5.  1.]
 [ 9.  5.]
 [12.  7.]
 [ 3.  2.]
 [ 8.  6.]
 [ 8.  9.]

In [145]:
#
# We next separate into test data and training data ... 
#    + We will train on the training data...
#    + We will _not_ look at the testing data to build the model
#
# Then, afterward, we will test on the testing data -- and see how well we do!
#

#
# a common convention:  train on 80%, test on 20%    Let's define the TEST_PERCENT
#
NUM_ROWS = X_labeled.shape[0]     # the number of labeled rows
TEST_PERCENT = 0.20
TEST_SIZE = int(TEST_PERCENT*NUM_ROWS)   # no harm in rounding down

X_test = X_labeled[:TEST_SIZE]    # first section are for testing
y_test = y_labeled[:TEST_SIZE]

X_train = X_labeled[TEST_SIZE:]   # all the rest are for training
y_train = y_labeled[TEST_SIZE:]

print(f"training with {len(y_train)} rows;  testing with {len(y_test)} rows" )

training with 298 rows;  testing with 74 rows


In [146]:
print(X_train)

[[11.  3.]
 [10. 22.]
 [ 3.  5.]
 [ 4. 23.]
 [12. 10.]
 [ 6. 28.]
 [12.  6.]
 [ 1.  4.]
 [10. 16.]
 [ 6. 19.]
 [12.  9.]
 [ 5.  1.]
 [ 9.  5.]
 [12.  7.]
 [ 3.  2.]
 [ 8.  6.]
 [ 8.  9.]
 [ 8. 25.]
 [ 5. 22.]
 [11. 21.]
 [ 5. 16.]
 [ 7.  4.]
 [ 9. 30.]
 [ 7. 21.]
 [ 2. 12.]
 [ 3. 24.]
 [ 2. 13.]
 [ 1. 14.]
 [12. 22.]
 [10. 24.]
 [10. 25.]
 [ 9.  1.]
 [11.  8.]
 [ 9.  9.]
 [ 4. 30.]
 [ 3. 25.]
 [ 4.  9.]
 [12. 13.]
 [ 9. 13.]
 [10. 20.]
 [ 2. 21.]
 [12. 12.]
 [10. 19.]
 [ 3. 29.]
 [ 4.  2.]
 [ 6. 23.]
 [11. 18.]
 [ 8.  4.]
 [10. 26.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7. 24.]
 [ 9.  8.]
 [ 4. 19.]
 [ 8. 14.]
 [ 9. 15.]
 [ 4. 21.]
 [ 6. 22.]
 [ 3. 21.]
 [ 4. 15.]
 [ 5.  6.]
 [10. 17.]
 [12. 25.]
 [ 4. 13.]
 [ 2.  7.]
 [11.  5.]
 [10. 12.]
 [ 2. 14.]
 [10.  4.]
 [11.  2.]
 [ 3.  7.]
 [ 8. 20.]
 [ 7. 12.]
 [11. 25.]
 [ 3. 17.]
 [ 9. 23.]
 [ 1. 11.]
 [11.  1.]
 [ 7. 20.]
 [11. 26.]
 [ 9. 25.]
 [ 1. 19.]
 [ 5. 29.]
 [ 8.  2.]
 [12. 30.]
 [ 2. 15.]
 [10.  9.]
 [11. 19.]
 [ 4. 11.]
 [ 8. 15.]
 [ 2. 27.]

In [147]:
#
# +++ This is the "Model-building and Model-training Cell"
#       
# Create a kNN model and train it! 
#
from sklearn.neighbors import KNeighborsClassifier

k = 150   # we don't know what k to use, so we guess!  (this will _not_ be a good value)
knn_model = KNeighborsClassifier(n_neighbors=k)       # here, k is the "k" in kNN

# we train the model (it's one line!)
knn_model.fit(X_train, y_train)                              # yay!  trained!
print("Created and trained a knn classifier with k =", k)  

Created and trained a knn classifier with k = 150


In [148]:
#
# +++ This is the "Model-testing Cell"
#
# Now, let's see how well we did on our "held-out data" (the testing data)
#

# We run our test set!
predicted_labels = knn_model.predict(X_test)
actual_labels = y_test

# Let's print them so we can compare...
print("Predicted labels:", predicted_labels)
print("Actual  labels  :", actual_labels)

# And, some overall results
num_correct = sum(predicted_labels == actual_labels)
total = len(actual_labels)
print(f"\nResults on test set:  {num_correct} correct out of {total} total.")

Predicted labels: [1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0.
 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.
 0. 1.]
Actual  labels  : [1. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 0.
 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 0. 1. 0.
 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0.
 1. 0.]

Results on test set:  53 correct out of 74 total.


In [149]:
#
# Let's print these more helpfully, in a vertical table
#

def compare_labels(predicted_labels, actual_labels):
    """ a more neatly formatted comparison """
    NUM_LABELS = len(predicted_labels)
    num_correct = 0
    
    for i in range(NUM_LABELS):
        p = int(round(predicted_labels[i]))         # round protects from fp error 
        a = int(round(actual_labels[i]))
        result = "incorrect"
        if p == a:  # if they match,
            result = ""       # no longer incorrect
            num_correct += 1  # and we count a match!

        print(f"row {i:>3d} : {MEDIAN[p]:>12s} {MEDIAN[a]:<12s}   {result}")   

    print()
    print("Correct:", num_correct, "out of", NUM_LABELS)
    return num_correct

In [150]:
#
# let's try it out!
#

compare_labels(predicted_labels,actual_labels)

row   0 :        above above          
row   1 :        below below          
row   2 :        below below          
row   3 :        above above          
row   4 :        above above          
row   5 :        below above          incorrect
row   6 :        below below          
row   7 :        above above          
row   8 :        below below          
row   9 :        above above          
row  10 :        below below          
row  11 :        below below          
row  12 :        above above          
row  13 :        above above          
row  14 :        below below          
row  15 :        below above          incorrect
row  16 :        above above          
row  17 :        above below          incorrect
row  18 :        above above          
row  19 :        below below          
row  20 :        above above          
row  21 :        below above          incorrect
row  22 :        above above          
row  23 :        below below          
row  24 :        below below

53

In [151]:
#
# Ok!  We have our knn model, we could just use it...
#

#
# data-driven predictive model (k-nearest-neighbor), using scikit-learn
#

def predictive_model( Features ):
    """ input: a list of four features 
                [ sepallen, sepalwid, petallen, petalwid ]
        output: the predicted species of iris, from
                  setosa (0), versicolor (1), virginica (2)
    """
    our_features = np.asarray([Features])                 # extra brackets needed
    predicted_species = knn_model.predict(our_features)
    
    predicted_species = int(round(predicted_species[0]))  # unpack one element
    name = MEDIAN[predicted_species]
    return f"{name} ({predicted_species})"
    
#
# Try it!
# 
# Features = eval(input("Enter new Features: "))
#
Features = [11,22]  # [5.8,2.7,4.1,1.0] [4.6,3.6,3.0,2.2] [6.7,3.3,5.7,2.1]
result = predictive_model( Features )
print(f"I predict {result} from Features {Features}")

I predict above (1) from Features [11, 22]


In [152]:
#
# to do this, we use "cross validation"
#

from sklearn.model_selection import cross_val_score

#
# cross-validation splits the training set into two pieces:
#   + model-building and model-validation. We'll use "build" and "validate"
#
best_k = 0
best_acc=0

for k in range(1,150):
    knn_cv_model = KNeighborsClassifier(n_neighbors=k)   # build knn_model for every k!
    cv_scores = cross_val_score( knn_cv_model, X_train, y_train, cv=5 )  # 5 means 80/20 split
    # print(cv_scores)  # just to see the five scores... 
    average_cv_accuracy = cv_scores.mean()  # mean() is numpy's built-in average function 
    if average_cv_accuracy > best_acc:
        best_k = k
        best_acc= average_cv_accuracy
        print("+++++best so fair!!!+++++")
    print(f"k: {k:2d}  cv accuracy: {average_cv_accuracy:7.4f}")

    
    
# assign best value of k to best_k
#best_k = k      # at the moment this is incorrect!   TO DO for hw4pr3: fix this...
# you'll need to use the loop above to find and remember the real best_k

print(f"best_k = {best_k}   yields the highest average cv accuracy.")  # print the best one

+++++best so fair!!!+++++
k:  1  cv accuracy:  0.8020
k:  2  cv accuracy:  0.7988
+++++best so fair!!!+++++
k:  3  cv accuracy:  0.8323
k:  4  cv accuracy:  0.8088
k:  5  cv accuracy:  0.8019
k:  6  cv accuracy:  0.8255
+++++best so fair!!!+++++
k:  7  cv accuracy:  0.8456
k:  8  cv accuracy:  0.8389
k:  9  cv accuracy:  0.8356
k: 10  cv accuracy:  0.8389
k: 11  cv accuracy:  0.8389
k: 12  cv accuracy:  0.8255
+++++best so fair!!!+++++
k: 13  cv accuracy:  0.8457
k: 14  cv accuracy:  0.8255
k: 15  cv accuracy:  0.8288
k: 16  cv accuracy:  0.8322
k: 17  cv accuracy:  0.8356
k: 18  cv accuracy:  0.8288
k: 19  cv accuracy:  0.8256
k: 20  cv accuracy:  0.8221
k: 21  cv accuracy:  0.8156
k: 22  cv accuracy:  0.8088
k: 23  cv accuracy:  0.7987
k: 24  cv accuracy:  0.8087
k: 25  cv accuracy:  0.7953
k: 26  cv accuracy:  0.7953
k: 27  cv accuracy:  0.7988
k: 28  cv accuracy:  0.7988
k: 29  cv accuracy:  0.7987
k: 30  cv accuracy:  0.7953
k: 31  cv accuracy:  0.7987
k: 32  cv accuracy:  0.7919


In [153]:
#
# Now, we re-create and re-run the  "Model-building and -training Cell"
#
# Now, using best_k instead of the original, randomly-guessed value    How does it do?!
#
from sklearn.neighbors import KNeighborsClassifier
knn_model_tuned = KNeighborsClassifier(n_neighbors=best_k)   # here, we use the best_k

# we train the model (one line!)
knn_model_tuned.fit(X_train, y_train)                              # yay!  trained!
print(f"Created + trained a knn classifier, now tuned with a (best) k of {best_k}")  

Created + trained a knn classifier, now tuned with a (best) k of 13


In [154]:
#
# Re-create and re-run the  "Model-testing Cell"     How does it do with best_k?!
#
predicted_labels = knn_model_tuned.predict(X_test)
actual_labels = y_test

# Let's print them so we can compare...
print("Predicted labels:", predicted_labels)
print("Actual labels:", actual_labels)
print()
# and, we'll print our nicer table...
compare_labels(predicted_labels,actual_labels)

Predicted labels: [1. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0.
 0. 0. 1. 1. 1. 0. 1. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0.
 0. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0.
 1. 1.]
Actual labels: [1. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 0.
 0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 0. 1. 0.
 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0.
 1. 0.]

row   0 :        above above          
row   1 :        below below          
row   2 :        below below          
row   3 :        above above          
row   4 :        above above          
row   5 :        above above          
row   6 :        below below          
row   7 :        above above          
row   8 :        below below          
row   9 :        above above          
row  10 :        below below          
row  11 :        below below          
row  12 :        above above          
row  

63

In [155]:
#
# Ok!  We have tuned knn to use the "best" value of k...
#
# And, we should really use ALL available data to train our final predictive model:
#

knn_model_final = KNeighborsClassifier(n_neighbors=best_k)   # here, we use the best_k
knn_model_final.fit(X_all, y_all)                              # yay!  trained!
print(f"Created + trained a 'final' knn classifier, with a (best) k of {best_k}") 

Created + trained a 'final' knn classifier, with a (best) k of 13


In [156]:
#
# final predictive model (k-nearest-neighbor), with tuned k + ALL data incorporated
#

def predictive_model( Features ):
    """ input: a list of four features 
                [ sepallen, sepalwid, petallen, petalwid ]
        output: the predicted species of iris, from
                  setosa (0), versicolor (1), virginica (2)
    """
    our_features = np.asarray([Features])                 # extra brackets needed
    predicted_species = knn_model_final.predict(our_features)
    
    predicted_species = int(round(predicted_species[0]))  # unpack one element
    name = MEDIAN[predicted_species]
    return f"{name} ({predicted_species})"
    
#
# Try it!
# 
# Features = eval(input("Enter new Features: "))
#
Features = [12,16]
result = predictive_model( Features )
print(f"I predict {result} from Features {Features}")

I predict above (1) from Features [12, 16]


In [157]:
Features_work = [
[10,4.2],
[1.5,1.5],
[2,-1],
[-10,0],
[0,0],
[2,32],
[9.2,6.5],
[3.14159,2.71828],
[42,42]
]

B=np.array(Features_work)

for i in range(len(B)):
    y=predictive_model( B[i] )
    print(f"I predict {y} from Features {B[i]}")



I predict above (1) from Features [10.   4.2]
I predict below (0) from Features [1.5 1.5]
I predict below (0) from Features [ 2. -1.]
I predict below (0) from Features [-10.   0.]
I predict below (0) from Features [0. 0.]
I predict below (0) from Features [ 2. 32.]
I predict above (1) from Features [9.2 6.5]
I predict below (0) from Features [3.14159 2.71828]
I predict below (0) from Features [42. 42.]


In [158]:
#
# try it on new data!  (grab it from the problem statement)
#
#
# TO DO for hw4pr3:
#       write a loop that will handle _multiple_ new flowers and predict their species...
#

In [159]:
#
# Be sure your results from trying this on the unknown data are here - or above!
#

In [160]:
#
# That's it!  Welcome to the world of model-building workflows!!    
#
#             Our prediction?  We'll be back for more ML! 
#

#
# In fact, the rest of the hw is to run more ML workflows:   Digits, Titanic, Housing, ...
#